/**************************************************************************************************\
 *** 
 *** Simulink model       : AltitudeObserver
 *** TargetLink subsystem : AltitudeObserver
 *** Codefile             : AltitudeObserver.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2018-08-06 10:52:04
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : disabled
 *** Logging mode                             : According to block-specific data
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Local_Code_Space\ControlModel\cconfig.xml
 *** Root style sheet                         : C:\Prg\dSpace\TargetLink4_2_64bit\Matlab\Tl\XML\Code
 ***                                            Gen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** SUBSYS                   CORRESPONDING SIMULINK SUBSYSTEM
 *** Sb1                      AltitudeObserver
 *** Sb2                      AltitudeObserver/createMeaurand
 *** Sb3                      AltitudeObserver/createMeaurand1
 *** Sb4                      AltitudeObserver/createMeaurand2
 *** Sb5                      AltitudeObserver/createMeaurand3
 *** Sb6                      AltitudeObserver/getValue
 *** Sb7                      AltitudeObserver/getValue1
 *** 
 *** SUBSYS                   CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE   CORRESPONDING STATEFLOW NODE                           DESCRIPTION
 *** 
 *** TargetLink version      : 4.2 from 14-Oct-2016
 *** Code generator version  : Build Id 4.2.0.26 from 2016-10-17 16:31:48
 *** 
 *** ########################################################################
 *** 
 *** This file is part of the I4Copter Control Model
 *** 
 *** Copyright (c) 2011-2012 Christian Harkort christian.harkort@fau.de (0)
 *** Copyright (c) 2012, 2015, 2018 Tobias Klaus klaus@cs.fau.de (1)
 *** 
 *** Affiliations
 *** 
 *** (0) Chair of Automatic Control
 ***     FAU Erlangen-Nuremberg
 *** (1) Chair of Distributed Systems and Operating Systems
 ***     FAU Erlangen-Nuremberg
 *** 
 *** The I4Copter Control model is free software: you can redistribute it
 *** and/or modify it under the terms of the GNU Affero General Public License,
 *** version 3, as published by the Free Software Foundation.
 *** 
 *** This program is distributed in the hope that it will be useful,
 *** but WITHOUT ANY WARRANTY; without even the implied warranty of
 *** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *** GNU Affero General Public License for more details.
 *** 
 *** You should have received a copy of the GNU Affero General Public License
 *** along with this project.  If not, see http://www.gnu.org/licenses/.
 *** 
 *** ########################################################################
 ***                 
\**************************************************************************************************/

#ifndef ALTITUDEOBSERVER_C
#define ALTITUDEOBSERVER_C

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include <math.h>
#include "tl_defines_b.h"
#include "AltitudeObserver.h"

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 32
\******************************************************************************/
Float32 In_altObs_AccZ_g_dsp_noiseVariance;
Float32 In_altObs_AccZ_g_dsp_processVariance;
Float32 In_altObs_AccZ_g_dsp_value;
Float32 In_altObs_Altitude_m_dsp_noiseVariance;
Float32 In_altObs_Altitude_m_dsp_processVariance;
Float32 In_altObs_Altitude_m_dsp_value;
Float32 In_altObs_AngleX_RAD_attObs;
Float32 In_altObs_AngleY_RAD_attObs;
Float32 In_altObs_ThrustZ_N_engCtr;
Float32 Out_AccZ_Mss_altObs_noiseVariance;
Float32 Out_AccZ_Mss_altObs_processVariance;
Float32 Out_AccZ_Mss_altObs_value;
Float32 Out_Altitude_m_altObs_noiseVariance;
Float32 Out_Altitude_m_altObs_processVariance;
Float32 Out_Altitude_m_altObs_value;
Float32 Out_VelocityZ_Ms_altObs_noiseVariance;
Float32 Out_VelocityZ_Ms_altObs_processVariance;
Float32 Out_VelocityZ_Ms_altObs_value;
Float32 Out_distZ_N_altObs_noiseVariance;
Float32 Out_distZ_N_altObs_processVariance;
Float32 Out_distZ_N_altObs_value;

/******************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 8
\******************************************************************************/
Bool In_altObs_AccZ_g_dsp_valid;
Bool In_altObs_Altitude_m_dsp_valid;
Bool In_altObs_TakeOff_engCtr;
Bool Out_AccZ_Mss_altObs_valid;
Bool Out_Altitude_m_altObs_valid;
Bool Out_VelocityZ_Ms_altObs_valid;
Bool Out_distZ_N_altObs_valid;

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      STEP_AltitudeObserver
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
void STEP_AltitudeObserver(void)
{
   /* CONST: global constants (ROM) | Width: 32 */
   CONST Float32 Gain = 4.3318171501159668F; /* MIN/MAX: 4.33181715011597 .. 4.33181715011597 */
   CONST Float32 Luenberg_a1 = 0.F; /* MIN/MAX: 0 .. 0 */
   CONST Float32 Luenberg_a2 = 0.F; /* MIN/MAX: 0 .. 0 */
   CONST Float32 Luenberg_a3 = 0.F; /* MIN/MAX: 0 .. 0 */
   CONST Float32 Luenberg_a4 = 0.F; /* MIN/MAX: 0 .. 0 */
   CONST Float32 Luenberg_h1 = 22.179561614990234F; /* MIN/MAX: 22.1795616149902 .. 22.1795616149902
    */
   CONST Float32 Luenberg_h2 = 131.16493225097656F; /* MIN/MAX: 131.164932250977 .. 131.164932250977
    */
   CONST Float32 Luenberg_h3 = 33.066463470458984F; /* MIN/MAX: 33.066463470459 .. 33.066463470459 */
   
   CONST Float32 Luenberg_h4 = 0.F; /* MIN/MAX: 0 .. 0 */
   CONST Float32 attentuation = 0.072403892874717712F; /* MIN/MAX: 0.0724038928747177 .. 0.072403892
   8747177 */
   CONST Float32 engine = 1.3500000238418579F; /* MIN/MAX: 1.35000002384186 .. 1.35000002384186 */

   /* SLLocal: Default storage class for local variables | Width: 32 */
   Float32 Sum3;
   Float32 Sum6;
   Float32 Switch;

   /* SLStaticLocalInit: Default storage class for static local variables with initvalue | Width: 32
    */
   static Float32 DiscreteTimeIntegrator = 0.F;
   static Float32 DiscreteTimeIntegrator1 = 0.F;
   static Float32 DiscreteTimeIntegrator2 = 0.F;
   static Float32 DiscreteTimeIntegrator3 = 0.F;

   /* BusOutport: AltitudeObserver/distZ_N_altObs
      # combined # Discrete Integrator: AltitudeObserver/Discrete-Time Integrator3 */
   Out_distZ_N_altObs_value = DiscreteTimeIntegrator3;

   /* BusOutport: AltitudeObserver/distZ_N_altObs */
   Out_distZ_N_altObs_noiseVariance = 0.F;
   Out_distZ_N_altObs_processVariance = 0.F;
   Out_distZ_N_altObs_valid = 1;

   /* Switch: AltitudeObserver/Switch
      AltitudeObserver/Switch: Omitted comparison with constant. */
   if (In_altObs_TakeOff_engCtr) {
      /* Switch: AltitudeObserver/Switch
         # combined # Sum: AltitudeObserver/Sum8
         # combined # Discrete Integrator: AltitudeObserver/Discrete-Time Integrator2 */
      Switch = DiscreteTimeIntegrator2 - 9.8062000274658203F;
   }
   else {
      /* Switch: AltitudeObserver/Switch */
      Switch = 0.F;
   }

   /* Sum: AltitudeObserver/Sum2
      # combined # BusOutport: AltitudeObserver/AccZ_Mss_altObs
      # combined # Gain: AltitudeObserver/attentuation
      # combined # Discrete Integrator: AltitudeObserver/Discrete-Time Integrator1 */
   Out_AccZ_Mss_altObs_value = Switch - (DiscreteTimeIntegrator1 * attentuation);

   /* BusOutport: AltitudeObserver/AccZ_Mss_altObs */
   Out_AccZ_Mss_altObs_noiseVariance = 0.F;
   Out_AccZ_Mss_altObs_processVariance = 0.F;
   Out_AccZ_Mss_altObs_valid = 1;

   /* BusOutport: AltitudeObserver/VelocityZ_Ms_altObs
      # combined # Discrete Integrator: AltitudeObserver/Discrete-Time Integrator1 */
   Out_VelocityZ_Ms_altObs_value = DiscreteTimeIntegrator1;

   /* BusOutport: AltitudeObserver/VelocityZ_Ms_altObs */
   Out_VelocityZ_Ms_altObs_noiseVariance = 0.F;
   Out_VelocityZ_Ms_altObs_processVariance = 0.F;
   Out_VelocityZ_Ms_altObs_valid = 1;

   /* BusOutport: AltitudeObserver/Altitude_m_altObs
      # combined # Discrete Integrator: AltitudeObserver/Discrete-Time Integrator */
   Out_Altitude_m_altObs_value = DiscreteTimeIntegrator;

   /* BusOutport: AltitudeObserver/Altitude_m_altObs */
   Out_Altitude_m_altObs_noiseVariance = 0.F;
   Out_Altitude_m_altObs_processVariance = 0.F;
   Out_Altitude_m_altObs_valid = 1;

   /* Sum: AltitudeObserver/Sum6
      # combined # BusOutport: AltitudeObserver/AccZ_Mss_altObs */
   Sum6 = In_altObs_AccZ_g_dsp_value - Out_AccZ_Mss_altObs_value;

   /* Sum: AltitudeObserver/Sum3
      # combined # Discrete Integrator: AltitudeObserver/Discrete-Time Integrator */
   Sum3 = In_altObs_Altitude_m_dsp_value - DiscreteTimeIntegrator;

   /* Discrete Integrator: integration
      # combined # Sum: AltitudeObserver/Sum1
      # combined # Discrete Integrator: AltitudeObserver/Discrete-Time Integrator1
      # combined # Gain: AltitudeObserver/Luenberg_h1
      # combined # Gain: AltitudeObserver/Luenberg_a1 */
   DiscreteTimeIntegrator += (((Sum6 * Luenberg_a1) + (Sum3 * Luenberg_h1) +
    DiscreteTimeIntegrator1) * 0.003F);

   /* Discrete Integrator: integration
      # combined # Sum: AltitudeObserver/Sum5
      # combined # BusOutport: AltitudeObserver/AccZ_Mss_altObs
      # combined # Gain: AltitudeObserver/Luenberg_h2
      # combined # Gain: AltitudeObserver/Luenberg_a2 */
   DiscreteTimeIntegrator1 += (((Sum6 * Luenberg_a2) + (Sum3 * Luenberg_h2) +
    Out_AccZ_Mss_altObs_value) * 0.003F);

   /* Discrete Integrator: integration
      # combined # Gain: AltitudeObserver/Gain
      # combined # Sum: AltitudeObserver/Sum7
      # combined # Sum: AltitudeObserver/Sum4
      # combined # Discrete Integrator: AltitudeObserver/Discrete-Time Integrator3
      # combined # Gain: AltitudeObserver/Luenberg_h3
      # combined # Gain: AltitudeObserver/Luenberg_a3
      # combined # Gain: AltitudeObserver/engine
      # combined # Product: AltitudeObserver/Product2
      # combined # Product: AltitudeObserver/Product1
      # combined # Trig: AltitudeObserver/Trigonometric Function4
      # combined # Trig: AltitudeObserver/Trigonometric Function3
      # combined # Discrete Integrator: AltitudeObserver/Discrete-Time Integrator2 */
   DiscreteTimeIntegrator2 += (((Sum6 * Luenberg_a3) + (Sum3 * Luenberg_h3) +
    DiscreteTimeIntegrator3 + ((((Float32) cos((Float64) In_altObs_AngleX_RAD_attObs)) * ((Float32)
    cos((Float64) In_altObs_AngleY_RAD_attObs)) * In_altObs_ThrustZ_N_engCtr) -
    (DiscreteTimeIntegrator2 * engine))) * Gain * 0.003F);

   /* Discrete Integrator: integration
      # combined # Sum: AltitudeObserver/Sum10
      # combined # Gain: AltitudeObserver/Luenberg_h4
      # combined # Gain: AltitudeObserver/Luenberg_a4 */
   DiscreteTimeIntegrator3 += (((Sum6 * Luenberg_a4) + (Sum3 * Luenberg_h4)) * 0.003F);
}

/*----------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/
#endif /* ALTITUDEOBSERVER_C */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
