/**************************************************************************************************\
 *** 
 *** Simulink model       : I4Copter
 *** TargetLink subsystem : I4Copter/HeightObserver
 *** Codefile             : HeightObserver.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2018-08-06 10:52:30
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : disabled
 *** Logging mode                             : According to block-specific data
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Local_Code_Space\ControlModel\cconfig.xml
 *** Root style sheet                         : C:\Prg\dSpace\TargetLink4_2_64bit\Matlab\Tl\XML\Code
 ***                                            Gen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** SUBSYS                   CORRESPONDING SIMULINK SUBSYSTEM
 *** Sc1                      HeightObserver
 *** Sc2                      HeightObserver/createMeaurand
 *** Sc3                      HeightObserver/createMeaurand1
 *** Sc4                      HeightObserver/createMeaurand2
 *** Sc5                      HeightObserver/createMeaurand3
 *** Sc6                      HeightObserver/getValue
 *** Sc7                      HeightObserver/getValue1
 *** 
 *** SUBSYS                   CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE   CORRESPONDING STATEFLOW NODE                           DESCRIPTION
 *** 
 *** TargetLink version      : 4.2 from 14-Oct-2016
 *** Code generator version  : Build Id 4.2.0.26 from 2016-10-17 16:31:48
 *** 
 *** ########################################################################
 *** 
 *** This file is part of the I4Copter Control Model
 *** 
 *** Copyright (c) 2011-2012 Christian Harkort christian.harkort@fau.de (0)
 *** Copyright (c) 2012, 2015, 2018 Tobias Klaus klaus@cs.fau.de (1)
 *** 
 *** Affiliations
 *** 
 *** (0) Chair of Automatic Control
 ***     FAU Erlangen-Nuremberg
 *** (1) Chair of Distributed Systems and Operating Systems
 ***     FAU Erlangen-Nuremberg
 *** 
 *** The I4Copter Control model is free software: you can redistribute it
 *** and/or modify it under the terms of the GNU Affero General Public License,
 *** version 3, as published by the Free Software Foundation.
 *** 
 *** This program is distributed in the hope that it will be useful,
 *** but WITHOUT ANY WARRANTY; without even the implied warranty of
 *** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *** GNU Affero General Public License for more details.
 *** 
 *** You should have received a copy of the GNU Affero General Public License
 *** along with this project.  If not, see http://www.gnu.org/licenses/.
 *** 
 *** ########################################################################
 ***                 
\**************************************************************************************************/

#ifndef HEIGHTOBSERVER_C
#define HEIGHTOBSERVER_C

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include <math.h>
#include "HeightObserver.h"

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   CAL: global calibratable parameters (ROM) | Width: 32
\******************************************************************************/
CAL Float32 VI_Gain_Value = 4.3318171501159668F;

/******************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 32
\******************************************************************************/
Float32 In_heiObs_Altitude_m_dsp_value;
Float32 In_heiObs_AngleX_RAD_attObs;
Float32 In_heiObs_AngleY_RAD_attObs;
Float32 In_heiObs_ThrustZ_N_engCtr;
Float32 Out_AccZ_Mss_heiObs_noiseVariance;
Float32 Out_AccZ_Mss_heiObs_processVariance;
Float32 Out_AccZ_Mss_heiObs_value;
Float32 Out_Altitude_m_heiObs_noiseVariance;
Float32 Out_Altitude_m_heiObs_processVariance;
Float32 Out_Altitude_m_heiObs_value;
Float32 Out_VelocityZ_Ms_heiObs_noiseVariance;
Float32 Out_VelocityZ_Ms_heiObs_processVariance;
Float32 Out_VelocityZ_Ms_heiObs_value;
Float32 Out_distZ_N_heiObs_noiseVariance;
Float32 Out_distZ_N_heiObs_processVariance;
Float32 Out_distZ_N_heiObs_value;

/******************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 8
\******************************************************************************/
Bool In_heiObs_TakeOff_engCtr;
Bool OutAccZ_Mss_heiObs_valid;
Bool Out_Altitude_m_heiObs_valid;
Bool Out_VelocityZ_Ms_heiObs_valid;
Bool Out_distZ_N_heiObs_valid;

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      STEP_HeightObserver
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
void STEP_HeightObserver(void)
{
   /* CONST: global constants (ROM) | Width: 32 */
   CONST Float32 attentuation = 0.072403892874717712F; /* MIN/MAX: 0.0724038928747177 .. 0.072403892
   8747177 */
   CONST Float32 engine = 1.3500000238418579F; /* MIN/MAX: 1.35000002384186 .. 1.35000002384186 */

   /* SLLocal: Default storage class for local variables | Width: 32 */
   Float32 Sum3;
   Float32 Switch;

   /* SLStaticLocalInit: Default storage class for static local variables with initvalue | Width: 32
    */
   static Float32 DiscreteTimeIntegrator = 0.F;
   static Float32 DiscreteTimeIntegrator1 = 0.F;
   static Float32 DiscreteTimeIntegrator2 = 1.F;
   static Float32 DiscreteTimeIntegrator3 = 0.F;

   /* BusOutport: HeightObserver/distZ_N_altObs
      # combined # Discrete Integrator: HeightObserver/Discrete-Time Integrator3 */
   Out_distZ_N_heiObs_value = DiscreteTimeIntegrator3;

   /* BusOutport: HeightObserver/distZ_N_altObs */
   Out_distZ_N_heiObs_noiseVariance = 0.F;
   Out_distZ_N_heiObs_processVariance = 0.F;
   Out_distZ_N_heiObs_valid = 1;

   /* Switch: HeightObserver/Switch
      HeightObserver/Switch: Omitted comparison with constant. */
   if (In_heiObs_TakeOff_engCtr) {
      /* Switch: HeightObserver/Switch
         # combined # Sum: HeightObserver/Sum8
         # combined # Discrete Integrator: HeightObserver/Discrete-Time Integrator2 */
      Switch = DiscreteTimeIntegrator2 - 9.8062000274658203F;
   }
   else {
      /* Switch: HeightObserver/Switch */
      Switch = 0.F;
   }

   /* Sum: HeightObserver/Sum2
      # combined # BusOutport: HeightObserver/AccZ_Mss_altObs
      # combined # Gain: HeightObserver/attentuation
      # combined # Discrete Integrator: HeightObserver/Discrete-Time Integrator1 */
   Out_AccZ_Mss_heiObs_value = Switch - (DiscreteTimeIntegrator1 * attentuation);

   /* BusOutport: HeightObserver/AccZ_Mss_altObs */
   Out_AccZ_Mss_heiObs_noiseVariance = 0.F;
   Out_AccZ_Mss_heiObs_processVariance = 0.F;
   OutAccZ_Mss_heiObs_valid = 1;

   /* BusOutport: HeightObserver/VelocityZ_Ms_altObs
      # combined # Discrete Integrator: HeightObserver/Discrete-Time Integrator1 */
   Out_VelocityZ_Ms_heiObs_value = DiscreteTimeIntegrator1;

   /* BusOutport: HeightObserver/VelocityZ_Ms_altObs */
   Out_VelocityZ_Ms_heiObs_noiseVariance = 0.F;
   Out_VelocityZ_Ms_heiObs_processVariance = 0.F;
   Out_VelocityZ_Ms_heiObs_valid = 1;

   /* BusOutport: HeightObserver/Altitude_m_altObs
      # combined # Discrete Integrator: HeightObserver/Discrete-Time Integrator */
   Out_Altitude_m_heiObs_value = DiscreteTimeIntegrator;

   /* BusOutport: HeightObserver/Altitude_m_altObs */
   Out_Altitude_m_heiObs_noiseVariance = 0.F;
   Out_Altitude_m_heiObs_processVariance = 0.F;
   Out_Altitude_m_heiObs_valid = 1;

   /* Sum: HeightObserver/Sum3
      # combined # Discrete Integrator: HeightObserver/Discrete-Time Integrator */
   Sum3 = In_heiObs_Altitude_m_dsp_value - DiscreteTimeIntegrator;

   /* Discrete Integrator: integration
      # combined # Sum: HeightObserver/Sum1
      # combined # Discrete Integrator: HeightObserver/Discrete-Time Integrator1 */
   DiscreteTimeIntegrator += (((Sum3 * 18.503885314680232F) + DiscreteTimeIntegrator1) * 0.003F);

   /* Discrete Integrator: integration
      # combined # Sum: HeightObserver/Sum5
      # combined # BusOutport: HeightObserver/AccZ_Mss_altObs */
   DiscreteTimeIntegrator1 += (((Sum3 * 84.420915836599775F) + Out_AccZ_Mss_heiObs_value) * 0.003F);

   /* Discrete Integrator: integration
      # combined # Gain: HeightObserver/Gain
      # combined # Sum: HeightObserver/Sum7
      # combined # Sum: HeightObserver/Sum4
      # combined # Discrete Integrator: HeightObserver/Discrete-Time Integrator3
      # combined # Gain: HeightObserver/engine
      # combined # Product: HeightObserver/Product2
      # combined # Product: HeightObserver/Product1
      # combined # Trig: HeightObserver/Trigonometric Function4
      # combined # Trig: HeightObserver/Trigonometric Function3
      # combined # Discrete Integrator: HeightObserver/Discrete-Time Integrator2 */
   DiscreteTimeIntegrator2 += (((Sum3 * 9.0298825679212396F) + DiscreteTimeIntegrator3 +
    ((((Float32) cos((Float64) In_heiObs_AngleX_RAD_attObs)) * ((Float32) cos((Float64)
    In_heiObs_AngleY_RAD_attObs)) * In_heiObs_ThrustZ_N_engCtr) - (DiscreteTimeIntegrator2 *
    engine))) * VI_Gain_Value * 0.003F);

   /* Discrete Integrator: integration
      # combined # Sum: HeightObserver/Sum10 */
   DiscreteTimeIntegrator3 += (Sum3 * 34.977272727273721F * 0.003F);
}

/*----------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/
#endif /* HEIGHTOBSERVER_C */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
