/**************************************************************************************************\
 *** 
 *** Simulink model       : EngineController
 *** TargetLink subsystem : EngineController
 *** Codefile             : EngineController.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2018-08-06 10:52:11
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : disabled
 *** Logging mode                             : According to block-specific data
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Local_Code_Space\ControlModel\cconfig.xml
 *** Root style sheet                         : C:\Prg\dSpace\TargetLink4_2_64bit\Matlab\Tl\XML\Code
 ***                                            Gen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** SUBSYS                   CORRESPONDING SIMULINK SUBSYSTEM
 *** Sb1                      EngineController
 *** Sb2                      EngineController/throttle-to-thrust/torque conversion
 *** Sb3                      EngineController/thrust/torque-to-throttle conversion
 *** 
 *** SUBSYS                   CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE   CORRESPONDING STATEFLOW NODE                           DESCRIPTION
 *** 
 *** TargetLink version      : 4.2 from 14-Oct-2016
 *** Code generator version  : Build Id 4.2.0.26 from 2016-10-17 16:31:48
 *** 
 *** ########################################################################
 *** 
 *** This file is part of the I4Copter Control Model
 *** 
 *** Copyright (c) 2011-2012 Christian Harkort christian.harkort@fau.de (0)
 *** Copyright (c) 2012, 2015, 2018 Tobias Klaus klaus@cs.fau.de (1)
 *** 
 *** Affiliations
 *** 
 *** (0) Chair of Automatic Control
 ***     FAU Erlangen-Nuremberg
 *** (1) Chair of Distributed Systems and Operating Systems
 ***     FAU Erlangen-Nuremberg
 *** 
 *** The I4Copter Control model is free software: you can redistribute it
 *** and/or modify it under the terms of the GNU Affero General Public License,
 *** version 3, as published by the Free Software Foundation.
 *** 
 *** This program is distributed in the hope that it will be useful,
 *** but WITHOUT ANY WARRANTY; without even the implied warranty of
 *** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *** GNU Affero General Public License for more details.
 *** 
 *** You should have received a copy of the GNU Affero General Public License
 *** along with this project.  If not, see http://www.gnu.org/licenses/.
 *** 
 *** ########################################################################
 ***                 
\**************************************************************************************************/

#ifndef ENGINECONTROLLER_C
#define ENGINECONTROLLER_C

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "tl_defines_b.h"
#include "EngineController_lut.h"
#include "EngineController.h"

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 32
\******************************************************************************/
Float32 In_engCtr_takeoff_g_sw;
Float32 In_engCtr_thrustZ_N_attCtr;
Float32 In_engCtr_torqueX_NM_attCtr;
Float32 In_engCtr_torqueY_NM_attCtr;
Float32 In_engCtr_torqueZ_NM_attCtr;
Float32 Out_throttleFront_engCtr;
Float32 Out_throttleLeft_engCtr;
Float32 Out_throttleRear_engCtr;
Float32 Out_throttleRight_engCtr;
Float32 Out_thrustZ_N_engCtr;
Float32 Out_torqueX_NM_engCtr;
Float32 Out_torqueY_NM_engCtr;

/******************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 8
\******************************************************************************/
Bool Out_takeOff_engCtr;

/******************************************************************************\
   SLGlobalConst: Default storage class for global const variables | Width: 32
\******************************************************************************/
const Float32 Sb2_Lookup_Table1_axis[10] = 
{
   /* [0..9] */ 0.F, 100.F, 200.F, 300.F, 400.F, 500.F, 600.F, 700.F, 800.F, 900.F
   /* 0.F, 100.F, 200.F, 300.F, 400.F, 500.F, 600.F, 700.F, 800.F, 900.F */
}; /* different constrained ranges */
const Float32 Sb2_Lookup_Table2_axis[10] = 
{
   /* [0..9] */ 0.F, 100.F, 200.F, 300.F, 400.F, 500.F, 600.F, 700.F, 800.F, 900.F
   /* 0.F, 100.F, 200.F, 300.F, 400.F, 500.F, 600.F, 700.F, 800.F, 900.F */
}; /* different constrained ranges */
const Float32 Sb2_Lookup_Table3_axis[10] = 
{
   /* [0..9] */ 0.F, 100.F, 200.F, 300.F, 400.F, 500.F, 600.F, 700.F, 800.F, 900.F
   /* 0.F, 100.F, 200.F, 300.F, 400.F, 500.F, 600.F, 700.F, 800.F, 900.F */
}; /* different constrained ranges */
const Float32 Sb2_Lookup_Table_axis[10] = 
{
   /* [0..9] */ 0.F, 100.F, 200.F, 300.F, 400.F, 500.F, 600.F, 700.F, 800.F, 900.F
   /* 0.F, 100.F, 200.F, 300.F, 400.F, 500.F, 600.F, 700.F, 800.F, 900.F */
}; /* different constrained ranges */
const Float32 Sb3_Lookup_Table_axis[10] = 
{
   /* [0..9] */ 0.F, 1.1771999597549438F, 2.3543999195098877F, 4.5128002166748047F,
    7.2199997901916504F, 10.633999824523926F, 13.890800476074219F, 16.755599975585938F,
    20.012399673461914F, 22.759199142456055F
   /* 0.F, 1.1771999597549438F, 2.3543999195098877F, 4.5128002166748047F, 7.2199997901916504F, 10.63
   3999824523926F, 13.890800476074219F, 16.755599975585938F, 20.012399673461914F, 22.759199142456055
   F */
}; /* different constrained ranges */
const Float32 tor_conv__Lookup_Table1_table[10] = 
{
   /* [0..9] */ 0.F, 0.29429998993873596F, 0.58859997987747192F, 1.1282000541687012F,
    1.8049999475479126F, 2.6584999561309814F, 3.4727001190185547F, 4.1888999938964844F,
    5.0030999183654785F, 5.6897997856140137F
   /* 0.F, 0.29429998993873596F, 0.58859997987747192F, 1.1282000541687012F, 1.8049999475479126F, 2.6
   584999561309814F, 3.4727001190185547F, 4.1888999938964844F, 5.0030999183654785F, 5.68979978561401
   37F */
}; /* different constrained ranges */
const Float32 tor_conv__Lookup_Table2_table[10] = 
{
   /* [0..9] */ 0.F, 0.29429998993873596F, 0.58859997987747192F, 1.1282000541687012F,
    1.8049999475479126F, 2.6584999561309814F, 3.4727001190185547F, 4.1888999938964844F,
    5.0030999183654785F, 5.6897997856140137F
   /* 0.F, 0.29429998993873596F, 0.58859997987747192F, 1.1282000541687012F, 1.8049999475479126F, 2.6
   584999561309814F, 3.4727001190185547F, 4.1888999938964844F, 5.0030999183654785F, 5.68979978561401
   37F */
}; /* different constrained ranges */
const Float32 tor_conv__Lookup_Table3_table[10] = 
{
   /* [0..9] */ 0.F, 0.29429998993873596F, 0.58859997987747192F, 1.1282000541687012F,
    1.8049999475479126F, 2.6584999561309814F, 3.4727001190185547F, 4.1888999938964844F,
    5.0030999183654785F, 5.6897997856140137F
   /* 0.F, 0.29429998993873596F, 0.58859997987747192F, 1.1282000541687012F, 1.8049999475479126F, 2.6
   584999561309814F, 3.4727001190185547F, 4.1888999938964844F, 5.0030999183654785F, 5.68979978561401
   37F */
}; /* different constrained ranges */
const Float32 tor_conv__Lookup_Table_table[10] = 
{
   /* [0..9] */ 0.F, 0.29429998993873596F, 0.58859997987747192F, 1.1282000541687012F,
    1.8049999475479126F, 2.6584999561309814F, 3.4727001190185547F, 4.1888999938964844F,
    5.0030999183654785F, 5.6897997856140137F
   /* 0.F, 0.29429998993873596F, 0.58859997987747192F, 1.1282000541687012F, 1.8049999475479126F, 2.6
   584999561309814F, 3.4727001190185547F, 4.1888999938964844F, 5.0030999183654785F, 5.68979978561401
   37F */
}; /* different constrained ranges */
const Float32 tor_to_thro_conv__Lookup_Table_table[10] = 
{
   /* [0..9] */ 0.F, 100.F, 200.F, 300.F, 400.F, 500.F, 600.F, 700.F, 800.F, 900.F
   /* 0.F, 100.F, 200.F, 300.F, 400.F, 500.F, 600.F, 700.F, 800.F, 900.F */
}; /* different constrained ranges */

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      STEP_EngineController
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
void STEP_EngineController(void)
{
   /* CONST: global constants (ROM) | Width: 32 */
   CONST Float32 tor_conv__Gain4 = 0.30000001192092896F; /* MIN/MAX: 0.300000011920929 .. 0.30000001
   1920929 */
   CONST Float32 tor_conv__Gain6 = 0.30000001192092896F; /* MIN/MAX: 0.300000011920929 .. 0.30000001
   1920929 */
   CONST Float32 tor_to_thro_conv__EngineCap1_uplimit = 843.29412841796875F; /* MIN/MAX: 843.2941284
   17969 .. 843.294128417969 */
   CONST Float32 tor_to_thro_conv__EngineCap2_uplimit = 843.29412841796875F; /* MIN/MAX: 843.2941284
   17969 .. 843.294128417969 */
   CONST Float32 tor_to_thro_conv__EngineCap3_uplimit = 843.29412841796875F; /* MIN/MAX: 843.2941284
   17969 .. 843.294128417969 */
   CONST Float32 tor_to_thro_conv__EngineCap4_uplimit = 843.29412841796875F; /* MIN/MAX: 843.2941284
   17969 .. 843.294128417969 */
   CONST Float32 tor_to_thro_conv__throttle_per_torqueX = 204.69990539550781F; /* MIN/MAX: 204.69990
   5395508 .. 204.699905395508 */
   CONST Float32 tor_to_thro_conv__throttle_per_torqueY = 204.69990539550781F; /* MIN/MAX: 204.69990
   5395508 .. 204.699905395508 */
   CONST Float32 tor_to_thro_conv__throttle_per_torqueZ = 66.928108215332031F; /* MIN/MAX: 66.928108
   215332 .. 66.928108215332 */

   /* SLLocal: Default storage class for local variables | Width: 32 */
   Float32 Sb2_Lookup_Table;
   Float32 Sb2_Lookup_Table1;
   Float32 Sb2_Lookup_Table2;
   Float32 Sb2_Lookup_Table3;
   Float32 Sb3_Lookup_Table;
   Float32 Sb3_throttle_per_torqueX;
   Float32 Sb3_throttle_per_torqueY;
   Float32 Sb3_throttle_per_torqueZ;
   Float32 tor_to_thro_conv__Sum4;
   Float32 tor_to_thro_conv__Sum5;
   Float32 tor_to_thro_conv__Sum6;
   Float32 tor_to_thro_conv__Sum7;

   /* SLStaticLocalConst: Default storage class for static local const variables | Width: N.A. */
   static const MAP_Tab1DS3I2T3126_b Sb2_Lookup_Table1_map = {
      10, /* Nx: Description: number of axis points */
      &(Sb2_Lookup_Table1_axis[0]), /* x_table: Description: vector with axis values */
      &(tor_conv__Lookup_Table1_table[0]) /* z_table: Description: vector with table values */
   };
   
   static const MAP_Tab1DS3I2T3126_b Sb2_Lookup_Table2_map = {
      10, /* Nx: Description: number of axis points */
      &(Sb2_Lookup_Table2_axis[0]), /* x_table: Description: vector with axis values */
      &(tor_conv__Lookup_Table2_table[0]) /* z_table: Description: vector with table values */
   };
   
   static const MAP_Tab1DS3I2T3126_b Sb2_Lookup_Table3_map = {
      10, /* Nx: Description: number of axis points */
      &(Sb2_Lookup_Table3_axis[0]), /* x_table: Description: vector with axis values */
      &(tor_conv__Lookup_Table3_table[0]) /* z_table: Description: vector with table values */
   };
   
   static const MAP_Tab1DS3I2T3126_b Sb2_Lookup_Table_map = {
      10, /* Nx: Description: number of axis points */
      &(Sb2_Lookup_Table_axis[0]), /* x_table: Description: vector with axis values */
      &(tor_conv__Lookup_Table_table[0]) /* z_table: Description: vector with table values */
   };
   
   static const MAP_Tab1DS3I2T3126_b Sb3_Lookup_Table_map = {
      10, /* Nx: Description: number of axis points */
      &(Sb3_Lookup_Table_axis[0]), /* x_table: Description: vector with axis values */
      &(tor_to_thro_conv__Lookup_Table_table[0]) /* z_table: Description: vector with table values */
      
   };

   /* Relational: EngineController/thrust__torque-to-throttle conversion/Relational Operator
      # combined # TargetLink outport: EngineController/takeOff_engCtr
      # combined # Product: EngineController/thrust__torque-to-throttle conversion/Product3 */
   Out_takeOff_engCtr = In_engCtr_thrustZ_N_attCtr > (In_engCtr_takeoff_g_sw * 13.238369941711426F);

   /* TableLookup: EngineController/thrust__torque-to-throttle conversion/Lookup Table */
   Sb3_Lookup_Table = Tab1DS3I2T3126_b(&Sb3_Lookup_Table_map, In_engCtr_thrustZ_N_attCtr);

   /* Gain: EngineController/thrust__torque-to-throttle conversion/throttle per torqueY
      # combined # Product: EngineController/thrust__torque-to-throttle conversion/Product2
      # combined # TargetLink outport: EngineController/takeOff_engCtr */
   Sb3_throttle_per_torqueY = In_engCtr_torqueY_NM_attCtr * ((Float32) Out_takeOff_engCtr) *
    tor_to_thro_conv__throttle_per_torqueY;

   /* Gain: EngineController/thrust__torque-to-throttle conversion/throttle per torqueZ
      # combined # Product: EngineController/thrust__torque-to-throttle conversion/Product
      # combined # TargetLink outport: EngineController/takeOff_engCtr */
   Sb3_throttle_per_torqueZ = In_engCtr_torqueZ_NM_attCtr * ((Float32) Out_takeOff_engCtr) *
    tor_to_thro_conv__throttle_per_torqueZ;

   /* Sum: EngineController/thrust__torque-to-throttle conversion/Sum5
      # combined # Sum: EngineController/thrust__torque-to-throttle conversion/Sum3 */
   tor_to_thro_conv__Sum5 = (Sb3_Lookup_Table - Sb3_throttle_per_torqueY) +
    Sb3_throttle_per_torqueZ;

   /* Saturation: EngineController/thrust__torque-to-throttle conversion/EngineCap4 */
   if (tor_to_thro_conv__Sum5 > tor_to_thro_conv__EngineCap4_uplimit) {
      /* # combined # TargetLink outport: EngineController/throttleRear_engCtr */
      Out_throttleRear_engCtr = tor_to_thro_conv__EngineCap4_uplimit;
   }
   else {
      /* CONST: global constants (ROM) | Width: 32 */
      CONST Float32 tor_to_thro_conv__EngineCap4_lowlimit = -40.156864166259766F; /* MIN/MAX: -40.15
      68641662598 .. -40.1568641662598 */

      if (tor_to_thro_conv__Sum5 < tor_to_thro_conv__EngineCap4_lowlimit) {
         /* # combined # TargetLink outport: EngineController/throttleRear_engCtr */
         Out_throttleRear_engCtr = tor_to_thro_conv__EngineCap4_lowlimit;
      }
      else {
         /* # combined # TargetLink outport: EngineController/throttleRear_engCtr */
         Out_throttleRear_engCtr = tor_to_thro_conv__Sum5;
      }
   }

   /* TableLookup: EngineController/throttle-to-thrust__torque conversion/Lookup Table
      # combined # TargetLink outport: EngineController/throttleRear_engCtr */
   Sb2_Lookup_Table = Tab1DS3I2T3126_b(&Sb2_Lookup_Table_map, Out_throttleRear_engCtr);

   /* Gain: EngineController/thrust__torque-to-throttle conversion/throttle per torqueX
      # combined # Product: EngineController/thrust__torque-to-throttle conversion/Product1
      # combined # TargetLink outport: EngineController/takeOff_engCtr */
   Sb3_throttle_per_torqueX = In_engCtr_torqueX_NM_attCtr * ((Float32) Out_takeOff_engCtr) *
    tor_to_thro_conv__throttle_per_torqueX;

   /* Sum: EngineController/thrust__torque-to-throttle conversion/Sum6
      # combined # Sum: EngineController/thrust__torque-to-throttle conversion/Sum2 */
   tor_to_thro_conv__Sum6 = Sb3_Lookup_Table - Sb3_throttle_per_torqueX - Sb3_throttle_per_torqueZ;

   /* Saturation: EngineController/thrust__torque-to-throttle conversion/EngineCap3 */
   if (tor_to_thro_conv__Sum6 > tor_to_thro_conv__EngineCap3_uplimit) {
      /* # combined # TargetLink outport: EngineController/throttleRight_engCtr */
      Out_throttleRight_engCtr = tor_to_thro_conv__EngineCap3_uplimit;
   }
   else {
      /* CONST: global constants (ROM) | Width: 32 */
      CONST Float32 tor_to_thro_conv__EngineCap3_lowlimit = -40.156864166259766F; /* MIN/MAX: -40.15
      68641662598 .. -40.1568641662598 */

      if (tor_to_thro_conv__Sum6 < tor_to_thro_conv__EngineCap3_lowlimit) {
         /* # combined # TargetLink outport: EngineController/throttleRight_engCtr */
         Out_throttleRight_engCtr = tor_to_thro_conv__EngineCap3_lowlimit;
      }
      else {
         /* # combined # TargetLink outport: EngineController/throttleRight_engCtr */
         Out_throttleRight_engCtr = tor_to_thro_conv__Sum6;
      }
   }

   /* TableLookup: EngineController/throttle-to-thrust__torque conversion/Lookup Table1
      # combined # TargetLink outport: EngineController/throttleRight_engCtr */
   Sb2_Lookup_Table1 = Tab1DS3I2T3126_b(&Sb2_Lookup_Table1_map, Out_throttleRight_engCtr);

   /* Sum: EngineController/thrust__torque-to-throttle conversion/Sum4
      # combined # Sum: EngineController/thrust__torque-to-throttle conversion/Sum1 */
   tor_to_thro_conv__Sum4 = Sb3_throttle_per_torqueZ + (Sb3_Lookup_Table +
    Sb3_throttle_per_torqueY);

   /* Saturation: EngineController/thrust__torque-to-throttle conversion/EngineCap2 */
   if (tor_to_thro_conv__Sum4 > tor_to_thro_conv__EngineCap2_uplimit) {
      /* # combined # TargetLink outport: EngineController/throttleFront_engCtr */
      Out_throttleFront_engCtr = tor_to_thro_conv__EngineCap2_uplimit;
   }
   else {
      /* CONST: global constants (ROM) | Width: 32 */
      CONST Float32 tor_to_thro_conv__EngineCap2_lowlimit = -40.156864166259766F; /* MIN/MAX: -40.15
      68641662598 .. -40.1568641662598 */

      if (tor_to_thro_conv__Sum4 < tor_to_thro_conv__EngineCap2_lowlimit) {
         /* # combined # TargetLink outport: EngineController/throttleFront_engCtr */
         Out_throttleFront_engCtr = tor_to_thro_conv__EngineCap2_lowlimit;
      }
      else {
         /* # combined # TargetLink outport: EngineController/throttleFront_engCtr */
         Out_throttleFront_engCtr = tor_to_thro_conv__Sum4;
      }
   }

   /* TableLookup: EngineController/throttle-to-thrust__torque conversion/Lookup Table2
      # combined # TargetLink outport: EngineController/throttleFront_engCtr */
   Sb2_Lookup_Table2 = Tab1DS3I2T3126_b(&Sb2_Lookup_Table2_map, Out_throttleFront_engCtr);

   /* Sum: EngineController/thrust__torque-to-throttle conversion/Sum7
      # combined # Sum: EngineController/thrust__torque-to-throttle conversion/Sum */
   tor_to_thro_conv__Sum7 = (Sb3_Lookup_Table + Sb3_throttle_per_torqueX) -
    Sb3_throttle_per_torqueZ;

   /* Saturation: EngineController/thrust__torque-to-throttle conversion/EngineCap1 */
   if (tor_to_thro_conv__Sum7 > tor_to_thro_conv__EngineCap1_uplimit) {
      /* # combined # TargetLink outport: EngineController/throttleLeft_engCtr */
      Out_throttleLeft_engCtr = tor_to_thro_conv__EngineCap1_uplimit;
   }
   else {
      /* CONST: global constants (ROM) | Width: 32 */
      CONST Float32 tor_to_thro_conv__EngineCap1_lowlimit = -40.156864166259766F; /* MIN/MAX: -40.15
      68641662598 .. -40.1568641662598 */

      if (tor_to_thro_conv__Sum7 < tor_to_thro_conv__EngineCap1_lowlimit) {
         /* # combined # TargetLink outport: EngineController/throttleLeft_engCtr */
         Out_throttleLeft_engCtr = tor_to_thro_conv__EngineCap1_lowlimit;
      }
      else {
         /* # combined # TargetLink outport: EngineController/throttleLeft_engCtr */
         Out_throttleLeft_engCtr = tor_to_thro_conv__Sum7;
      }
   }

   /* TableLookup: EngineController/throttle-to-thrust__torque conversion/Lookup Table3
      # combined # TargetLink outport: EngineController/throttleLeft_engCtr */
   Sb2_Lookup_Table3 = Tab1DS3I2T3126_b(&Sb2_Lookup_Table3_map, Out_throttleLeft_engCtr);

   /* TargetLink outport: EngineController/thrustZ_N_engCtr
      # combined # Sum: EngineController/throttle-to-thrust__torque conversion/Sum2 */
   Out_thrustZ_N_engCtr = Sb2_Lookup_Table + Sb2_Lookup_Table1 + Sb2_Lookup_Table2 +
    Sb2_Lookup_Table3;

   /* TargetLink outport: EngineController/torqueY_NM_engCtr
      # combined # Product: EngineController/throttle-to-thrust__torque conversion/Product1
      # combined # Gain: EngineController/throttle-to-thrust__torque conversion/Gain6
      # combined # TargetLink outport: EngineController/takeOff_engCtr
      # combined # Sum: EngineController/throttle-to-thrust__torque conversion/Sum12 */
   Out_torqueY_NM_engCtr = ((Float32) Out_takeOff_engCtr) * ((Sb2_Lookup_Table2 - Sb2_Lookup_Table)
    * tor_conv__Gain6);

   /* TargetLink outport: EngineController/torqueX_NM_engCtr
      # combined # Product: EngineController/throttle-to-thrust__torque conversion/Product
      # combined # Gain: EngineController/throttle-to-thrust__torque conversion/Gain4
      # combined # TargetLink outport: EngineController/takeOff_engCtr
      # combined # Sum: EngineController/throttle-to-thrust__torque conversion/Sum3 */
   Out_torqueX_NM_engCtr = ((Float32) Out_takeOff_engCtr) * ((Sb2_Lookup_Table3 - Sb2_Lookup_Table1)
     * tor_conv__Gain4);
}

/*----------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/
#endif /* ENGINECONTROLLER_C */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
