/**************************************************************************************************\
 *** 
 *** Simulink model       : EngineController
 *** TargetLink subsystem : EngineController
 *** Codefile             : EngineController_lut.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2018-08-06 10:52:11
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : disabled
 *** Logging mode                             : According to block-specific data
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Local_Code_Space\ControlModel\cconfig.xml
 *** Root style sheet                         : C:\Prg\dSpace\TargetLink4_2_64bit\Matlab\Tl\XML\Code
 ***                                            Gen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** SUBSYS                   CORRESPONDING SIMULINK SUBSYSTEM
 *** Sb1                      EngineController
 *** Sb2                      EngineController/throttle-to-thrust/torque conversion
 *** Sb3                      EngineController/thrust/torque-to-throttle conversion
 *** 
 *** SUBSYS                   CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE   CORRESPONDING STATEFLOW NODE                           DESCRIPTION
 *** 
 *** TargetLink version      : 4.2 from 14-Oct-2016
 *** Code generator version  : Build Id 4.2.0.26 from 2016-10-17 16:31:48
 *** 
 *** ########################################################################
 *** 
 *** This file is part of the I4Copter Control Model
 *** 
 *** Copyright (c) 2011-2012 Christian Harkort christian.harkort@fau.de (0)
 *** Copyright (c) 2012, 2015, 2018 Tobias Klaus klaus@cs.fau.de (1)
 *** 
 *** Affiliations
 *** 
 *** (0) Chair of Automatic Control
 ***     FAU Erlangen-Nuremberg
 *** (1) Chair of Distributed Systems and Operating Systems
 ***     FAU Erlangen-Nuremberg
 *** 
 *** The I4Copter Control model is free software: you can redistribute it
 *** and/or modify it under the terms of the GNU Affero General Public License,
 *** version 3, as published by the Free Software Foundation.
 *** 
 *** This program is distributed in the hope that it will be useful,
 *** but WITHOUT ANY WARRANTY; without even the implied warranty of
 *** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *** GNU Affero General Public License for more details.
 *** 
 *** You should have received a copy of the GNU Affero General Public License
 *** along with this project.  If not, see http://www.gnu.org/licenses/.
 *** 
 *** ########################################################################
 ***                 
\**************************************************************************************************/

#ifndef ENGINECONTROLLER_LUT_C
#define ENGINECONTROLLER_LUT_C

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "EngineController_lut.h"

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Tab1DS3I2T3126_b
 *** 
 ***  DESCRIPTION:
 ***      Generated function for look-up tables.
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      const MAP_Tab1DS3I2T3126_b *map                 data structure
 ***      Float32            x                   table input
 ***
 ***  RETURNS:
 ***      Float32
 ***
 ***  SETTINGS:
 ***      Search algorithm...................: binary search
 ***      Look-up method.....................: Interpolation - Use end values
 ***      Distances fit into given bitlengths: no
 ***      Behavior at boundaries.............: no
 ***      Starting point.....................: - (non-equidistant implementation)
 ***      Scaling unit.......................: - (non-equidistant implementation)
 ***
\**************************************************************************************************/
Float32 Tab1DS3I2T3126_b(const MAP_Tab1DS3I2T3126_b * map, Float32 x)
{
   /* SLLocal: Default storage class for local variables | Width: 8 */
   UInt8 Aux_U8;
   UInt8 Aux_U8_a;
   UInt8 Aux_U8_b;

   /* SLLutLocalConst: Default storage class for local variables | Width: 32 */
   const Float32 * x_table; /* Scaling may differ through function reuse. */
   const Float32 * z_table; /* Scaling may differ through function reuse. */

   x_table = map->x_table;
   z_table = map->z_table;
   if (x <= *x_table) {
      /* Saturation. */
      return z_table[0];
   }
   if (x >= x_table[(UInt8) (map->Nx - 1)]) {
      return z_table[(UInt8) (map->Nx - 1)];
   }
   Aux_U8 = 0;

   /* Binary search. */
   Aux_U8_a = (UInt8) (map->Nx - 1);
   do {
      Aux_U8_b = (UInt8) (UInt16) (((UInt16) (((UInt16) Aux_U8) + ((UInt16) Aux_U8_a))) >> 1);
      if (x < x_table[Aux_U8_b]) {
         Aux_U8_a = Aux_U8_b;
      }
      else {
         Aux_U8 = Aux_U8_b;
      }
   }
   while (((Int16) Aux_U8) < ((Int16) (((Int16) Aux_U8_a) - 1)));
   x_table += Aux_U8;
   z_table += Aux_U8;

   /* Interpolation. */
   return (z_table[0] + (((z_table[1] - z_table[0]) * (x - x_table[0])) / (x_table[1] -
    x_table[0])));
}

/*----------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/
#endif /* ENGINECONTROLLER_LUT_C */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
