/**************************************************************************************************\
 *** 
 *** Simulink model       : AltitudeController
 *** TargetLink subsystem : AltitudeController
 *** Codefile             : AltitudeController.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2018-08-06 10:52:07
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : disabled
 *** Logging mode                             : According to block-specific data
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Local_Code_Space\ControlModel\cconfig.xml
 *** Root style sheet                         : C:\Prg\dSpace\TargetLink4_2_64bit\Matlab\Tl\XML\Code
 ***                                            Gen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** SUBSYS                   CORRESPONDING SIMULINK SUBSYSTEM
 *** Sb1                      AltitudeController
 *** Sb2                      AltitudeController/getValue
 *** Sb3                      AltitudeController/getValue1
 *** Sb4                      AltitudeController/getValue2
 *** 
 *** SUBSYS                   CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE   CORRESPONDING STATEFLOW NODE                           DESCRIPTION
 *** 
 *** TargetLink version      : 4.2 from 14-Oct-2016
 *** Code generator version  : Build Id 4.2.0.26 from 2016-10-17 16:31:48
 *** 
 *** ########################################################################
 *** 
 *** This file is part of the I4Copter Control Model
 *** 
 *** Copyright (c) 2011-2012 Christian Harkort christian.harkort@fau.de (0)
 *** Copyright (c) 2012, 2015, 2018 Tobias Klaus klaus@cs.fau.de (1)
 *** 
 *** Affiliations
 *** 
 *** (0) Chair of Automatic Control
 ***     FAU Erlangen-Nuremberg
 *** (1) Chair of Distributed Systems and Operating Systems
 ***     FAU Erlangen-Nuremberg
 *** 
 *** The I4Copter Control model is free software: you can redistribute it
 *** and/or modify it under the terms of the GNU Affero General Public License,
 *** version 3, as published by the Free Software Foundation.
 *** 
 *** This program is distributed in the hope that it will be useful,
 *** but WITHOUT ANY WARRANTY; without even the implied warranty of
 *** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *** GNU Affero General Public License for more details.
 *** 
 *** You should have received a copy of the GNU Affero General Public License
 *** along with this project.  If not, see http://www.gnu.org/licenses/.
 *** 
 *** ########################################################################
 ***                 
\**************************************************************************************************/

#ifndef ALTITUDECONTROLLER_C
#define ALTITUDECONTROLLER_C

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "tl_defines_b.h"
#include "AltitudeController.h"

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 32
\******************************************************************************/
Float32 In_altCtr_AccZ_g_altObs_noiseVariance;
Float32 In_altCtr_AccZ_g_altObs_processVariance;
Float32 In_altCtr_AccZ_g_altObs_value;
Float32 In_altCtr_AccZ_g_rem;
Float32 In_altCtr_Altitude_m_altObs_noiseVariance;
Float32 In_altCtr_Altitude_m_altObs_processVariance;
Float32 In_altCtr_Altitude_m_altObs_value;
Float32 In_altCtr_Altitude_m_rem;
Float32 In_altCtr_VelocityZ_Ms_altObs_noiseVariance;
Float32 In_altCtr_VelocityZ_Ms_altObs_processVariance;
Float32 In_altCtr_VelocityZ_Ms_altObs_value;
Float32 In_altCtr_VelocityZ_Ms_rem;
Float32 Out_ThrustZ_g_altCon;

/******************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 8
\******************************************************************************/
Bool In_altCtr_AccZ_g_altObs_valid;
Bool In_altCtr_Altitude_m_altObs_valid;
Bool In_altCtr_VelocityZ_Ms_altObs_valid;

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      STEP_AltitudeController
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
void STEP_AltitudeController(void)
{
   /* CONST: global constants (ROM) | Width: 32 */
   CONST Float32 Controller_influence_uplimit = 0.30000001192092896F; /* MIN/MAX: 0.300000011920929 
   .. 0.300000011920929 */
   CONST Float32 Kh_con[3] = 
   {
      /* [0..2] */ 1.0696853399276733F, 0.86713325977325439F, 0.079547576606273651F
      /* 1.0696853399276733F, 0.86713325977325439F, 0.079547576606273651F */
   }; /* different constrained ranges */

   /* SLLocal: Default storage class for local variables | Width: 32 */
   Float32 Sb1_Kh_con;

   /* Gain: AltitudeController/Kh_con
      # combined # Sum: AltitudeController/Sum1
      # combined # Sum: AltitudeController/Sum2
      # combined # Sum: AltitudeController/Sum3 */
   Sb1_Kh_con = (Kh_con[0] * (In_altCtr_Altitude_m_altObs_value - In_altCtr_Altitude_m_rem)) +
    (Kh_con[1] * (In_altCtr_VelocityZ_Ms_altObs_value - In_altCtr_VelocityZ_Ms_rem)) + (Kh_con[2] *
    (In_altCtr_AccZ_g_altObs_value - In_altCtr_AccZ_g_rem));

   /* Saturation: AltitudeController/Controller influence */
   if (Sb1_Kh_con > Controller_influence_uplimit) {
      /* # combined # TargetLink outport: AltitudeController/ThrustZ_g_altCon */
      Out_ThrustZ_g_altCon = Controller_influence_uplimit;
   }
   else {
      /* CONST: global constants (ROM) | Width: 32 */
      CONST Float32 Controller_influence_lowlimit = -0.30000001192092896F; /* MIN/MAX: -0.3000000119
      20929 .. -0.300000011920929 */

      if (Sb1_Kh_con < Controller_influence_lowlimit) {
         /* # combined # TargetLink outport: AltitudeController/ThrustZ_g_altCon */
         Out_ThrustZ_g_altCon = Controller_influence_lowlimit;
      }
      else {
         /* # combined # TargetLink outport: AltitudeController/ThrustZ_g_altCon */
         Out_ThrustZ_g_altCon = Sb1_Kh_con;
      }
   }
}

/*----------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/
#endif /* ALTITUDECONTROLLER_C */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
