/**************************************************************************************************\
 *** 
 *** Simulink model       : AttitudeController
 *** TargetLink subsystem : AttitudeController
 *** Codefile             : AttitudeController.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2018-08-06 10:52:09
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : disabled
 *** Logging mode                             : According to block-specific data
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Local_Code_Space\ControlModel\cconfig.xml
 *** Root style sheet                         : C:\Prg\dSpace\TargetLink4_2_64bit\Matlab\Tl\XML\Code
 ***                                            Gen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** SUBSYS                   CORRESPONDING SIMULINK SUBSYSTEM
 *** Sa1                      AttitudeController
 *** Sa2                      AttitudeController/controller about  X-axis
 *** Sa3                      AttitudeController/controller about Y-axis
 *** Sa4                      AttitudeController/controller about Z-axis
 *** Sa5                      AttitudeController/throttle correction
 *** 
 *** SUBSYS                   CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE   CORRESPONDING STATEFLOW NODE                           DESCRIPTION
 *** 
 *** TargetLink version      : 4.2 from 14-Oct-2016
 *** Code generator version  : Build Id 4.2.0.26 from 2016-10-17 16:31:48
 *** 
 *** ########################################################################
 *** 
 *** This file is part of the I4Copter Control Model
 *** 
 *** Copyright (c) 2011-2012 Christian Harkort christian.harkort@fau.de (0)
 *** Copyright (c) 2012, 2015, 2018 Tobias Klaus klaus@cs.fau.de (1)
 *** 
 *** Affiliations
 *** 
 *** (0) Chair of Automatic Control
 ***     FAU Erlangen-Nuremberg
 *** (1) Chair of Distributed Systems and Operating Systems
 ***     FAU Erlangen-Nuremberg
 *** 
 *** The I4Copter Control model is free software: you can redistribute it
 *** and/or modify it under the terms of the GNU Affero General Public License,
 *** version 3, as published by the Free Software Foundation.
 *** 
 *** This program is distributed in the hope that it will be useful,
 *** but WITHOUT ANY WARRANTY; without even the implied warranty of
 *** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *** GNU Affero General Public License for more details.
 *** 
 *** You should have received a copy of the GNU Affero General Public License
 *** along with this project.  If not, see http://www.gnu.org/licenses/.
 *** 
 *** ########################################################################
 ***                 
\**************************************************************************************************/

#ifndef ATTITUDECONTROLLER_C
#define ATTITUDECONTROLLER_C

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "tl_defines_a.h"
#include "AttitudeController.h"

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 32
\******************************************************************************/
Float32 In_attCtr_angleX_RAD_rem;
Float32 In_attCtr_angleY_RAD_rem;
Float32 In_attCtr_angularRateZ_RADs_dsp;
Float32 In_attCtr_angularRateZ_RADs_rem;
Float32 In_attCtr_statesX_attObs_angle;
Float32 In_attCtr_statesX_attObs_angularRate;
Float32 In_attCtr_statesX_attObs_angularState1;
Float32 In_attCtr_statesX_attObs_angularState2;
Float32 In_attCtr_statesY_attObs_angle;
Float32 In_attCtr_statesY_attObs_angularRate;
Float32 In_attCtr_statesY_attObs_angularState1;
Float32 In_attCtr_statesY_attObs_angularState2;
Float32 In_attCtr_thrustZ_g_rem;
Float32 Out_thrustZ_N_attCtr;
Float32 Out_torqueX_NM_attCtr;
Float32 Out_torqueY_NM_attCtr;
Float32 Out_torqueZ_NM_attCtr;

/******************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 8
\******************************************************************************/
Bool In_attCtr_takeOff_engCtr;

/******************************************************************************\
   SLStaticGlobal: Default storage class for global static variables | Width: 32
\******************************************************************************/
static Float32 Sa2_Saturation;
static Float32 Sa3_Saturation;
static Float32 Sa4_Yaw_Controller;
static Float32 Sa5_conversion_g____N;

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   StaticFcnSpecStep: Default function class for static model step functions
\******************************************************************************/
static void Sa2_controller_about__X_axis(void);

static void Sa3_controller_about_Y_axis(void);

static void Sa4_controller_about_Z_axis(void);

static void Sa5_throttle_correction(void);

/*----------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      STEP_AttitudeController
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
void STEP_AttitudeController(void)
{
   /* call of function: AttitudeController/controller about Z-axis */
   Sa4_controller_about_Z_axis();

   /* TargetLink outport: AttitudeController/torqueZ_NM_attCtr */
   Out_torqueZ_NM_attCtr = Sa4_Yaw_Controller;

   /* call of function: AttitudeController/controller about Y-axis */
   Sa3_controller_about_Y_axis();

   /* TargetLink outport: AttitudeController/torqueY_NM_attCtr */
   Out_torqueY_NM_attCtr = Sa3_Saturation;

   /* call of function: AttitudeController/controller about  X-axis */
   Sa2_controller_about__X_axis();

   /* TargetLink outport: AttitudeController/torqueX_NM_attCtr */
   Out_torqueX_NM_attCtr = Sa2_Saturation;

   /* call of function: AttitudeController/throttle correction */
   Sa5_throttle_correction();

   /* TargetLink outport: AttitudeController/thrustZ_N_attCtr */
   Out_thrustZ_N_attCtr = Sa5_conversion_g____N;
}

/*----------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Sa2_controller_about__X_axis
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
static void Sa2_controller_about__X_axis(void)
{
   /* CONST: global constants (ROM) | Width: 32 */
   CONST Float32 about_x_axis__Gain = 0.31622776389122009F; /* MIN/MAX: 0.31622776389122 .. 0.316227
   76389122 */
   CONST Float32 about_x_axis__Gain1[4] = 
   {
      /* [0..3] */ 0.074004270136356354F, 1.2385836839675903F, 0.34660369157791138F,
       0.84806334972381592F
      /* 0.074004270136356354F, 1.2385836839675903F, 0.34660369157791138F, 0.84806334972381592F */
   }; /* different constrained ranges */
   CONST Float32 about_x_axis__Saturation_uplimit = 11.289999961853027F; /* MIN/MAX: 11.289999961853
    .. 11.289999961853 */
   CONST Float32 about_x_axis__VorfilterY_denom[5] = 
   {
      /* [0..4] */ 1.F, -3.5743893884340645F, 4.7910973125562677F, -2.8542078988260138F,
       0.63762815162177444F
      /* 1.F, -3.5743893884340645F, 4.7910973125562677F, -2.8542078988260138F, 0.63762815162177444F */
      
   }; /* different constrained ranges */
   CONST Float32 about_x_axis__VorfilterY_num[5] = 
   {
      /* [0..4] */ 1.2965899658203126F, -4.0578720640810007F, 4.5117159524391992F,
       -2.0311894602341813F, 0.28085133760824793F
      /* 1.2965899658203126F, -4.0578720640810007F, 4.5117159524391992F, -2.0311894602341813F, 0.280
      85133760824793F */
   }; /* different constrained ranges */

   /* SLLocal: Default storage class for local variables | Width: 32 */
   Float32 Sa2_VorfilterY;
   Float32 about_x_axis__Sum1;

   /* SLStaticLocalInit: Default storage class for static local variables with initvalue | Width: 32
    */
   static Float32 X_Sa2_VorfilterY[8] = 
   {
      /* [0..7] */ 0.F, 0.F, 0.F, 0.F, 0.F, 0.F, 0.F, 0.F
      /* 0.F, 0.F, 0.F, 0.F, 0.F, 0.F, 0.F, 0.F */
   };
   static Float32 about_x_axis__DiscreteTimeIntegrator = 0.F;

   /* Discrete Transfer Function: output */
   Sa2_VorfilterY = (((-about_x_axis__VorfilterY_denom[1]) * X_Sa2_VorfilterY[0]) +
    ((-about_x_axis__VorfilterY_denom[2]) * X_Sa2_VorfilterY[1]) +
    ((-about_x_axis__VorfilterY_denom[3]) * X_Sa2_VorfilterY[2]) +
    ((-about_x_axis__VorfilterY_denom[4]) * X_Sa2_VorfilterY[3]) + (about_x_axis__VorfilterY_num[1]
    * X_Sa2_VorfilterY[4]) + (about_x_axis__VorfilterY_num[2] * X_Sa2_VorfilterY[5]) +
    (about_x_axis__VorfilterY_num[3] * X_Sa2_VorfilterY[6]) + (about_x_axis__VorfilterY_num[4] *
    X_Sa2_VorfilterY[7]) + (about_x_axis__VorfilterY_num[0] * In_attCtr_angleX_RAD_rem)) / 
    about_x_axis__VorfilterY_denom[0];
   X_Sa2_VorfilterY[7] = X_Sa2_VorfilterY[6];
   X_Sa2_VorfilterY[6] = X_Sa2_VorfilterY[5];
   X_Sa2_VorfilterY[5] = X_Sa2_VorfilterY[4];
   X_Sa2_VorfilterY[4] = In_attCtr_angleX_RAD_rem;
   X_Sa2_VorfilterY[3] = X_Sa2_VorfilterY[2];
   X_Sa2_VorfilterY[2] = X_Sa2_VorfilterY[1];
   X_Sa2_VorfilterY[1] = X_Sa2_VorfilterY[0];
   X_Sa2_VorfilterY[0] = Sa2_VorfilterY;

   /* Sum: AttitudeController/controller about  X-axis/Sum1
      # combined # Gain: AttitudeController/controller about  X-axis/Gain1
      # combined # Sum: AttitudeController/controller about  X-axis/Sum
      # combined # Discrete Integrator: AttitudeController/controller about  X-axis/Discrete-Time In
      tegrator
      # combined # Product: AttitudeController/controller about  X-axis/Product1
      # combined # Product: AttitudeController/controller about  X-axis/Product1
      # combined # Product: AttitudeController/controller about  X-axis/Product1
      # combined # Product: AttitudeController/controller about  X-axis/Product1 */
   about_x_axis__Sum1 = (Sa2_VorfilterY + about_x_axis__DiscreteTimeIntegrator) -
    ((about_x_axis__Gain1[0] * (((Float32) In_attCtr_takeOff_engCtr) *
    In_attCtr_statesX_attObs_angularState1)) + (about_x_axis__Gain1[1] * (((Float32)
    In_attCtr_takeOff_engCtr) * In_attCtr_statesX_attObs_angularState2)) + (about_x_axis__Gain1[2] *
     (((Float32) In_attCtr_takeOff_engCtr) * In_attCtr_statesX_attObs_angularRate)) +
    (about_x_axis__Gain1[3] * (((Float32) In_attCtr_takeOff_engCtr) *
    In_attCtr_statesX_attObs_angle)));

   /* Discrete Integrator: integration
      # combined # Gain: AttitudeController/controller about  X-axis/Gain
      # combined # Product: AttitudeController/controller about  X-axis/Product
      # combined # Sum: AttitudeController/controller about  X-axis/Sum7 */
   about_x_axis__DiscreteTimeIntegrator += (((Float32) In_attCtr_takeOff_engCtr) *
    (In_attCtr_angleX_RAD_rem - In_attCtr_statesX_attObs_angle) * about_x_axis__Gain * 0.009F);

   /* Saturation: AttitudeController/controller about  X-axis/Saturation */
   if (about_x_axis__Sum1 > about_x_axis__Saturation_uplimit) {
      Sa2_Saturation = about_x_axis__Saturation_uplimit;
   }
   else {
      /* CONST: global constants (ROM) | Width: 32 */
      CONST Float32 about_x_axis__Saturation_lowlimit = -11.289999961853027F; /* MIN/MAX: -11.289999
      961853 .. -11.289999961853 */

      if (about_x_axis__Sum1 < about_x_axis__Saturation_lowlimit) {
         Sa2_Saturation = about_x_axis__Saturation_lowlimit;
      }
      else {
         Sa2_Saturation = about_x_axis__Sum1;
      }
   }
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Sa3_controller_about_Y_axis
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
static void Sa3_controller_about_Y_axis(void)
{
   /* CONST: global constants (ROM) | Width: 32 */
   CONST Float32 about_y_axis__Gain = 0.31622776389122009F; /* MIN/MAX: 0.31622776389122 .. 0.316227
   76389122 */
   CONST Float32 about_y_axis__Gain1[4] = 
   {
      /* [0..3] */ 0.07328101247549057F, 1.2256289720535278F, 0.34962508082389832F,
       0.84918922185897827F
      /* 0.07328101247549057F, 1.2256289720535278F, 0.34962508082389832F, 0.84918922185897827F */
   }; /* different constrained ranges */
   CONST Float32 about_y_axis__Saturation_uplimit = 1.2899999618530273F; /* MIN/MAX: 1.2899999618530
   3 .. 1.28999996185303 */
   CONST Float32 about_y_axis__VorfilterX_denom[5] = 
   {
      /* [0..4] */ 1.F, -3.5743894577026367F, 4.7910971641540527F, -2.8542079925537109F,
       0.63762813806533813F
      /* 1.F, -3.5743894577026367F, 4.7910971641540527F, -2.8542079925537109F, 0.63762813806533813F */
      
   }; /* different constrained ranges */
   CONST Float32 about_y_axis__VorfilterX_num[5] = 
   {
      /* [0..4] */ 1.3265441656112671F, -4.1525959968566895F, 4.6181626319885254F,
       -2.0796828269958496F, 0.28766784071922302F
      /* 1.3265441656112671F, -4.1525959968566895F, 4.6181626319885254F, -2.0796828269958496F, 0.287
      66784071922302F */
   }; /* different constrained ranges */

   /* SLLocal: Default storage class for local variables | Width: 32 */
   Float32 Sa3_VorfilterX;
   Float32 about_y_axis__Sum1;

   /* SLStaticLocalInit: Default storage class for static local variables with initvalue | Width: 32
    */
   static Float32 X_Sa3_VorfilterX[8] = 
   {
      /* [0..7] */ 0.F, 0.F, 0.F, 0.F, 0.F, 0.F, 0.F, 0.F
      /* 0.F, 0.F, 0.F, 0.F, 0.F, 0.F, 0.F, 0.F */
   };
   static Float32 about_y_axis__DiscreteTimeIntegrator = 0.F;

   /* Discrete Transfer Function: output */
   Sa3_VorfilterX = (((-about_y_axis__VorfilterX_denom[1]) * X_Sa3_VorfilterX[0]) +
    ((-about_y_axis__VorfilterX_denom[2]) * X_Sa3_VorfilterX[1]) +
    ((-about_y_axis__VorfilterX_denom[3]) * X_Sa3_VorfilterX[2]) +
    ((-about_y_axis__VorfilterX_denom[4]) * X_Sa3_VorfilterX[3]) + (about_y_axis__VorfilterX_num[1]
    * X_Sa3_VorfilterX[4]) + (about_y_axis__VorfilterX_num[2] * X_Sa3_VorfilterX[5]) +
    (about_y_axis__VorfilterX_num[3] * X_Sa3_VorfilterX[6]) + (about_y_axis__VorfilterX_num[4] *
    X_Sa3_VorfilterX[7]) + (about_y_axis__VorfilterX_num[0] * In_attCtr_angleY_RAD_rem)) / 
    about_y_axis__VorfilterX_denom[0];
   X_Sa3_VorfilterX[7] = X_Sa3_VorfilterX[6];
   X_Sa3_VorfilterX[6] = X_Sa3_VorfilterX[5];
   X_Sa3_VorfilterX[5] = X_Sa3_VorfilterX[4];
   X_Sa3_VorfilterX[4] = In_attCtr_angleY_RAD_rem;
   X_Sa3_VorfilterX[3] = X_Sa3_VorfilterX[2];
   X_Sa3_VorfilterX[2] = X_Sa3_VorfilterX[1];
   X_Sa3_VorfilterX[1] = X_Sa3_VorfilterX[0];
   X_Sa3_VorfilterX[0] = Sa3_VorfilterX;

   /* Sum: AttitudeController/controller about Y-axis/Sum1
      # combined # Gain: AttitudeController/controller about Y-axis/Gain1
      # combined # Sum: AttitudeController/controller about Y-axis/Sum
      # combined # Discrete Integrator: AttitudeController/controller about Y-axis/Discrete-Time Int
      egrator
      # combined # Product: AttitudeController/controller about Y-axis/Product1
      # combined # Product: AttitudeController/controller about Y-axis/Product1
      # combined # Product: AttitudeController/controller about Y-axis/Product1
      # combined # Product: AttitudeController/controller about Y-axis/Product1 */
   about_y_axis__Sum1 = (Sa3_VorfilterX + about_y_axis__DiscreteTimeIntegrator) -
    ((about_y_axis__Gain1[0] * (((Float32) In_attCtr_takeOff_engCtr) *
    In_attCtr_statesY_attObs_angularState1)) + (about_y_axis__Gain1[1] * (((Float32)
    In_attCtr_takeOff_engCtr) * In_attCtr_statesY_attObs_angularState2)) + (about_y_axis__Gain1[2] *
     (((Float32) In_attCtr_takeOff_engCtr) * In_attCtr_statesY_attObs_angularRate)) +
    (about_y_axis__Gain1[3] * (((Float32) In_attCtr_takeOff_engCtr) *
    In_attCtr_statesY_attObs_angle)));

   /* Discrete Integrator: integration
      # combined # Gain: AttitudeController/controller about Y-axis/Gain
      # combined # Product: AttitudeController/controller about Y-axis/Product
      # combined # Sum: AttitudeController/controller about Y-axis/Sum7 */
   about_y_axis__DiscreteTimeIntegrator += (((Float32) In_attCtr_takeOff_engCtr) *
    (In_attCtr_angleY_RAD_rem - In_attCtr_statesY_attObs_angle) * about_y_axis__Gain * 0.009F);

   /* Saturation: AttitudeController/controller about Y-axis/Saturation */
   if (about_y_axis__Sum1 > about_y_axis__Saturation_uplimit) {
      Sa3_Saturation = about_y_axis__Saturation_uplimit;
   }
   else {
      /* CONST: global constants (ROM) | Width: 32 */
      CONST Float32 about_y_axis__Saturation_lowlimit = -1.2899999618530273F; /* MIN/MAX: -1.2899999
      6185303 .. -1.28999996185303 */

      if (about_y_axis__Sum1 < about_y_axis__Saturation_lowlimit) {
         Sa3_Saturation = about_y_axis__Saturation_lowlimit;
      }
      else {
         Sa3_Saturation = about_y_axis__Sum1;
      }
   }
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Sa4_controller_about_Z_axis
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
static void Sa4_controller_about_Z_axis(void)
{
   /* CONST: global constants (ROM) | Width: 32 */
   CONST Float32 about_z_axis__DiscreteTransferFcn2_denom[2] = 
   {
      /* [0..1] */ 1.F, -0.97044553354850815F
      /* 1.F, -0.97044553354850815F */
   }; /* different constrained ranges */
   CONST Float32 about_z_axis__DiscreteTransferFcn2_num[2] = 
   {
      /* [0..1] */ 0.F, 0.029554466451491825F
      /* 0.F, 0.029554466451491825F */
   }; /* different constrained ranges */

   /* SLLocal: Default storage class for local variables | Width: 32 */
   Float32 about_z_axis__Product;

   /* SLStaticLocalInit: Default storage class for static local variables with initvalue | Width: 32
    */
   static Float32 X_Sa4_Discrete_Transfer_Fcn2[2] = 
   {
      /* [0..1] */ 0.F, 0.F
      /* 0.F, 0.F */
   };
   static Float32 X_Sa4_Yaw_Controller[2] = 
   {
      /* [0..1] */ 0.F, 0.F
      /* 0.F, 0.F */
   };

   /* Discrete Transfer Function: output */
   X_Sa4_Discrete_Transfer_Fcn2[0] = (((-about_z_axis__DiscreteTransferFcn2_denom[1]) *
    X_Sa4_Discrete_Transfer_Fcn2[0]) + (about_z_axis__DiscreteTransferFcn2_num[1] *
    X_Sa4_Discrete_Transfer_Fcn2[1]) + (about_z_axis__DiscreteTransferFcn2_num[0] *
    In_attCtr_angularRateZ_RADs_dsp)) / about_z_axis__DiscreteTransferFcn2_denom[0];
   X_Sa4_Discrete_Transfer_Fcn2[1] = In_attCtr_angularRateZ_RADs_dsp;

   /* Product: AttitudeController/controller about Z-axis/Product
      # combined # Sum: AttitudeController/controller about Z-axis/Sum3 */
   about_z_axis__Product = (In_attCtr_angularRateZ_RADs_rem + X_Sa4_Discrete_Transfer_Fcn2[0]) *
    ((Float32) In_attCtr_takeOff_engCtr);

   /* Discrete Transfer Function: output */
   Sa4_Yaw_Controller = (0.87430293291975336F * X_Sa4_Yaw_Controller[0]) + (-9.8743029329197523F *
    X_Sa4_Yaw_Controller[1]) + (10.F * about_z_axis__Product);
   X_Sa4_Yaw_Controller[0] = Sa4_Yaw_Controller;
   X_Sa4_Yaw_Controller[1] = about_z_axis__Product;
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Sa5_throttle_correction
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
static void Sa5_throttle_correction(void)
{
   /* CONST: global constants (ROM) | Width: 32 */
   CONST Float32 throttle_corr__conversion_g_N = 13.238369941711426F; /* MIN/MAX: 13.2383699417114 .
   . 13.2383699417114 */

   /* Gain: AttitudeController/throttle correction/conversion g -> N */
   Sa5_conversion_g____N = In_attCtr_thrustZ_g_rem * throttle_corr__conversion_g_N;
}

#endif /* ATTITUDECONTROLLER_C */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
