/**************************************************************************************************\
 *** 
 *** Simulink model       : AttitudeController
 *** TargetLink subsystem : AttitudeController
 *** Codefile             : AttitudeController.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2018-08-06 10:52:09
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : disabled
 *** Logging mode                             : According to block-specific data
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Local_Code_Space\ControlModel\cconfig.xml
 *** Root style sheet                         : C:\Prg\dSpace\TargetLink4_2_64bit\Matlab\Tl\XML\Code
 ***                                            Gen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 4.2 from 14-Oct-2016
 *** Code generator version  : Build Id 4.2.0.26 from 2016-10-17 16:31:48
 *** 
 *** ########################################################################
 *** 
 *** This file is part of the I4Copter Control Model
 *** 
 *** Copyright (c) 2011-2012 Christian Harkort christian.harkort@fau.de (0)
 *** Copyright (c) 2012, 2015, 2018 Tobias Klaus klaus@cs.fau.de (1)
 *** 
 *** Affiliations
 *** 
 *** (0) Chair of Automatic Control
 ***     FAU Erlangen-Nuremberg
 *** (1) Chair of Distributed Systems and Operating Systems
 ***     FAU Erlangen-Nuremberg
 *** 
 *** The I4Copter Control model is free software: you can redistribute it
 *** and/or modify it under the terms of the GNU Affero General Public License,
 *** version 3, as published by the Free Software Foundation.
 *** 
 *** This program is distributed in the hope that it will be useful,
 *** but WITHOUT ANY WARRANTY; without even the implied warranty of
 *** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *** GNU Affero General Public License for more details.
 *** 
 *** You should have received a copy of the GNU Affero General Public License
 *** along with this project.  If not, see http://www.gnu.org/licenses/.
 *** 
 *** ########################################################################
 ***                 
\**************************************************************************************************/

#ifndef ATTITUDECONTROLLER_H
#define ATTITUDECONTROLLER_H

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "tl_basetypes.h"

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 32
\******************************************************************************/
extern Float32 In_attCtr_angleX_RAD_rem;
extern Float32 In_attCtr_angleY_RAD_rem;
extern Float32 In_attCtr_angularRateZ_RADs_dsp;
extern Float32 In_attCtr_angularRateZ_RADs_rem;
extern Float32 In_attCtr_statesX_attObs_angle;
extern Float32 In_attCtr_statesX_attObs_angularRate;
extern Float32 In_attCtr_statesX_attObs_angularState1;
extern Float32 In_attCtr_statesX_attObs_angularState2;
extern Float32 In_attCtr_statesY_attObs_angle;
extern Float32 In_attCtr_statesY_attObs_angularRate;
extern Float32 In_attCtr_statesY_attObs_angularState1;
extern Float32 In_attCtr_statesY_attObs_angularState2;
extern Float32 In_attCtr_thrustZ_g_rem;
extern Float32 Out_thrustZ_N_attCtr;
extern Float32 Out_torqueX_NM_attCtr;
extern Float32 Out_torqueY_NM_attCtr;
extern Float32 Out_torqueZ_NM_attCtr;

/******************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 8
\******************************************************************************/
extern Bool In_attCtr_takeOff_engCtr;

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   GlobalFcnSpecStep: Default function class for not static model step functions
\******************************************************************************/
extern void STEP_AttitudeController(void);

#endif /* ATTITUDECONTROLLER_H */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
