#!/usr/bin/env python3
# -*-coding: utf-8 -*-
"""
Call wrapper for the cAMP.py script.
"""
import subprocess
import sys

print('Starting cAMP for ERTS2020 I4Copter example!')

command = ['python3 ../../MMHT/MMHT.py', ]

# Include Astree data flow results
command.append('--astree ../astree_output/I4Copter_DataFlowReport.csv')
# Include modified ARXML file generated by ASSIST
command.append('--arxml ../autosar/I4Copter.arxml')
# Include contraints put on the system
command.append('--spec ../specification/I4Copter_BindingConstraints.txt')
# Include declaration of calibration and measurement variables
command.append('--a2l ../autosar/I4Copter.a2l')
# Include memory map file
command.append('--memory_layout ../specification/AurixTC277_MemMap.csv')
# Include directory of the MatLab/Target Link model
command.append('--dir ../../ControlModel')
# Specify result saving of intermediate analysis step
command.append('-s ./I4Copter_Aggregation.pickle')
# Specify result saving of the cAMP 
command.append('--result ./I4Copter_BindingResults.csv')

cAMP_command = ' '.join(command)
subprocess.call(cAMP_command, shell=True)
