/**************************************************************************************************\
 *** 
 *** Simulink model       : AttitudeObserver
 *** TargetLink subsystem : AttitudeObserver
 *** Codefile             : AttitudeObserver.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2018-08-06 10:52:06
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : disabled
 *** Logging mode                             : According to block-specific data
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Local_Code_Space\ControlModel\cconfig.xml
 *** Root style sheet                         : C:\Prg\dSpace\TargetLink4_2_64bit\Matlab\Tl\XML\Code
 ***                                            Gen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** SUBSYS                   CORRESPONDING SIMULINK SUBSYSTEM
 *** Sc1                      AttitudeObserver
 *** Sc2                      AttitudeObserver/attitude observer X-axis
 *** Sc3                      AttitudeObserver/attitude observer Y-axis
 *** Sc4                      AttitudeObserver/getValue
 *** Sc5                      AttitudeObserver/getValue1
 *** Sc6                      AttitudeObserver/getValue2
 *** Sc7                      AttitudeObserver/getValue3
 *** 
 *** SUBSYS                   CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE   CORRESPONDING STATEFLOW NODE                           DESCRIPTION
 *** 
 *** TargetLink version      : 4.2 from 14-Oct-2016
 *** Code generator version  : Build Id 4.2.0.26 from 2016-10-17 16:31:48
 *** 
 *** ########################################################################
 *** 
 *** This file is part of the I4Copter Control Model
 *** 
 *** Copyright (c) 2011-2012 Christian Harkort christian.harkort@fau.de (0)
 *** Copyright (c) 2012, 2015, 2018 Tobias Klaus klaus@cs.fau.de (1)
 *** 
 *** Affiliations
 *** 
 *** (0) Chair of Automatic Control
 ***     FAU Erlangen-Nuremberg
 *** (1) Chair of Distributed Systems and Operating Systems
 ***     FAU Erlangen-Nuremberg
 *** 
 *** The I4Copter Control model is free software: you can redistribute it
 *** and/or modify it under the terms of the GNU Affero General Public License,
 *** version 3, as published by the Free Software Foundation.
 *** 
 *** This program is distributed in the hope that it will be useful,
 *** but WITHOUT ANY WARRANTY; without even the implied warranty of
 *** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *** GNU Affero General Public License for more details.
 *** 
 *** You should have received a copy of the GNU Affero General Public License
 *** along with this project.  If not, see http://www.gnu.org/licenses/.
 *** 
 *** ########################################################################
 ***                 
\**************************************************************************************************/

#ifndef ATTITUDEOBSERVER_C
#define ATTITUDEOBSERVER_C

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include <math.h>
#include "AttitudeObserver.h"

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   CAL: global calibratable parameters (ROM) | Width: 32
\******************************************************************************/
CAL Float32 x_axis__VI_Gain[3] = 
{
   /* [0..2] */ 0.86493286641956202F, 0.27386127875258409F, 0.73125089760685491F
   /* 0.86493286641956202F, 0.27386127875258409F, 0.73125089760685491F */
};

/******************************************************************************\
   DISP: global observable variables (RAM) | Width: 32
\******************************************************************************/
DISP Float32 x_axis__VI_Integrator = 0.F;

/******************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 32
\******************************************************************************/
Float32 In_attObs_accX_g_dsp_noiseVariance;
Float32 In_attObs_accX_g_dsp_processVariance;
Float32 In_attObs_accX_g_dsp_value;
Float32 In_attObs_accY_g_dsp_noiseVariance;
Float32 In_attObs_accY_g_dsp_processVariance;
Float32 In_attObs_accY_g_dsp_value;
Float32 In_attObs_angularRateX_RADs_dsp_noiseVariance;
Float32 In_attObs_angularRateX_RADs_dsp_processVariance;
Float32 In_attObs_angularRateX_RADs_dsp_value;
Float32 In_attObs_angularRateY_RADs_dsp_noiseVariance;
Float32 In_attObs_angularRateY_RADs_dsp_processVariance;
Float32 In_attObs_angularRateY_RADs_dsp_value;
Float32 In_attObs_torqueX_NM_engCtr;
Float32 In_attObs_torqueY_NM_engCtr;
Float32 Out_angleX_RAD_attObs;
Float32 Out_angleY_RAD_attObs;
Float32 Out_angularRateX_RADs_attObs;
Float32 Out_angularRateY_RADs_attObs;
Float32 Out_angularStatesX_attObs_angle;
Float32 Out_angularStatesX_attObs_angularRate;
Float32 Out_angularStatesX_attObs_angularState1;
Float32 Out_angularStatesX_attObs_angularState2;
Float32 Out_angularStatesY_attObs_angle;
Float32 Out_angularStatesY_attObs_angularRate;
Float32 Out_angularStatesY_attObs_angularState1;
Float32 Out_angularStatesY_attObs_angularState2;

/******************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 8
\******************************************************************************/
Bool In_attObs_accX_g_dsp_valid;
Bool In_attObs_accY_g_dsp_valid;
Bool In_attObs_angularRateX_RADs_dsp_valid;
Bool In_attObs_angularRateY_RADs_dsp_valid;
Bool In_attObs_takeOff_engCtr;

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      STEP_AttitudeObserver
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
void STEP_AttitudeObserver(void)
{
   /* SLLocal: Default storage class for local variables | Width: 32 */
   Float32 Sc2_Saturation;
   Float32 Sc3_Saturation;
   Float32 x_axis__Sum1;
   Float32 x_axis__Sum2;
   Float32 x_axis__TrigonometricFunction4;
   Float32 y_axis__Sum1;
   Float32 y_axis__Sum2;
   Float32 y_axis__TrigonometricFunction4;

   /* SLStaticLocalInit: Default storage class for static local variables with initvalue | Width: 32
    */
   static Float32 x_axis__DiscreteTimeIntegrator2 = 0.F;
   static Float32 x_axis__DiscreteTimeIntegrator3 = 0.F;
   static Float32 x_axis__DiscreteTimeIntegrator4 = 0.F;
   static Float32 x_axis__DiscreteTimeIntegrator5 = 0.F;
   static Float32 x_axis__DiscreteTimeIntegrator6 = 0.F;
   static Float32 x_axis__DiscreteTimeIntegrator7 = 0.F;
   static Float32 y_axis__DiscreteTimeIntegrator1 = 0.F;
   static Float32 y_axis__DiscreteTimeIntegrator2 = 0.F;
   static Float32 y_axis__DiscreteTimeIntegrator3 = 0.F;
   static Float32 y_axis__DiscreteTimeIntegrator4 = 0.F;
   static Float32 y_axis__DiscreteTimeIntegrator5 = 0.F;
   static Float32 y_axis__DiscreteTimeIntegrator6 = 0.F;
   static Float32 y_axis__DiscreteTimeIntegrator7 = 0.F;

   /* TargetLink outport: AttitudeObserver/angleY_RAD_attObs
      # combined # Gain: AttitudeObserver/attitude observer Y-axis/Gain8
      Variable 'Sc3_Gain8' replaced by 'Aux__a' */
   Out_angleY_RAD_attObs = y_axis__DiscreteTimeIntegrator3;

   /* TargetLink outport: AttitudeObserver/angularRateY_RADs_attObs
      # combined # Discrete Integrator: AttitudeObserver/attitude observer Y-axis/Discrete-Time Inte
      grator6 */
   Out_angularRateY_RADs_attObs = y_axis__DiscreteTimeIntegrator6;

   /* Gain: AttitudeObserver/attitude observer X-axis/Gain6
      Variable 'Sc2_Gain6' replaced by 'Aux_'
      # combined # BusOutport: AttitudeObserver/angularStatesX_attObs
      # combined # Discrete Integrator: AttitudeObserver/attitude observer X-axis/Discrete-Time Inte
      grator1 */
   Out_angularStatesX_attObs_angle = x_axis__DiscreteTimeIntegrator3 + (0.F *
    x_axis__VI_Integrator);

   /* TargetLink outport: AttitudeObserver/angleX_RAD_attObs
      # combined # BusOutport: AttitudeObserver/angularStatesX_attObs */
   Out_angleX_RAD_attObs = Out_angularStatesX_attObs_angle;

   /* TargetLink outport: AttitudeObserver/angularRateX_RADs_attObs
      # combined # Discrete Integrator: AttitudeObserver/attitude observer X-axis/Discrete-Time Inte
      grator6 */
   Out_angularRateX_RADs_attObs = x_axis__DiscreteTimeIntegrator6;

   /* BusOutport: AttitudeObserver/angularStatesY_attObs
      # combined # Discrete Integrator: AttitudeObserver/attitude observer Y-axis/Discrete-Time Inte
      grator4 */
   Out_angularStatesY_attObs_angularState1 = y_axis__DiscreteTimeIntegrator4;

   /* BusOutport: AttitudeObserver/angularStatesY_attObs
      # combined # Discrete Integrator: AttitudeObserver/attitude observer Y-axis/Discrete-Time Inte
      grator5 */
   Out_angularStatesY_attObs_angularState2 = y_axis__DiscreteTimeIntegrator5;

   /* BusOutport: AttitudeObserver/angularStatesY_attObs
      # combined # Discrete Integrator: AttitudeObserver/attitude observer Y-axis/Discrete-Time Inte
      grator6 */
   Out_angularStatesY_attObs_angularRate = y_axis__DiscreteTimeIntegrator6;

   /* BusOutport: AttitudeObserver/angularStatesY_attObs
      # combined # Gain: AttitudeObserver/attitude observer Y-axis/Gain8
      Variable 'Sc3_Gain8' replaced by 'Aux__a' */
   Out_angularStatesY_attObs_angle = y_axis__DiscreteTimeIntegrator3;

   /* BusOutport: AttitudeObserver/angularStatesX_attObs
      # combined # Discrete Integrator: AttitudeObserver/attitude observer X-axis/Discrete-Time Inte
      grator4 */
   Out_angularStatesX_attObs_angularState1 = x_axis__DiscreteTimeIntegrator4;

   /* BusOutport: AttitudeObserver/angularStatesX_attObs
      # combined # Discrete Integrator: AttitudeObserver/attitude observer X-axis/Discrete-Time Inte
      grator5 */
   Out_angularStatesX_attObs_angularState2 = x_axis__DiscreteTimeIntegrator5;

   /* BusOutport: AttitudeObserver/angularStatesX_attObs
      # combined # Discrete Integrator: AttitudeObserver/attitude observer X-axis/Discrete-Time Inte
      grator6 */
   Out_angularStatesX_attObs_angularRate = x_axis__DiscreteTimeIntegrator6;

   /* Saturation: AttitudeObserver/attitude observer Y-axis/Saturation */
   if (In_attObs_accX_g_dsp_value > 1.2F) {
      Sc3_Saturation = 1.2F;
   }
   else {
      if (In_attObs_accX_g_dsp_value < -1.2F) {
         Sc3_Saturation = -1.2F;
      }
      else {
         Sc3_Saturation = In_attObs_accX_g_dsp_value;
      }
   }

   /* Trig: AttitudeObserver/attitude observer Y-axis/Trigonometric Function4 */
   if (Sc3_Saturation < -1.F) {
      y_axis__TrigonometricFunction4 = -1.5707963267948966F;
   }
   else {
      if (Sc3_Saturation <= 1.F) {
         y_axis__TrigonometricFunction4 = (Float32) asin((Float64) Sc3_Saturation);
      }
      else {
         y_axis__TrigonometricFunction4 = 1.5707963267948966F;
      }
   }

   /* Sum: AttitudeObserver/attitude observer Y-axis/Sum2
      # combined # Gain: AttitudeObserver/attitude observer Y-axis/Gain8 */
   y_axis__Sum2 = y_axis__TrigonometricFunction4 - y_axis__DiscreteTimeIntegrator2;

   /* Discrete Integrator: integration
      # combined # Sum: AttitudeObserver/attitude observer Y-axis/Sum4
      # combined # Gain: AttitudeObserver/attitude observer Y-axis/Gain7
      # combined # Discrete Integrator: AttitudeObserver/attitude observer Y-axis/Discrete-Time Inte
      grator3
      # combined # Discrete Integrator: AttitudeObserver/attitude observer Y-axis/Discrete-Time Inte
      grator2 */
   y_axis__DiscreteTimeIntegrator2 += (((0.73125089760685491F * y_axis__Sum2) + ((2.F *
    y_axis__DiscreteTimeIntegrator3) + (-2.F * y_axis__DiscreteTimeIntegrator2))) * 0.003F);

   /* Discrete Integrator: integration
      # combined # Sum: AttitudeObserver/attitude observer Y-axis/Sum4
      Variable 'y_axis__Sum4' replaced by 'Aux__c'
      # combined # Gain: AttitudeObserver/attitude observer Y-axis/Gain7
      # combined # Gain: AttitudeObserver/attitude observer Y-axis/Gain5
      # combined # Gain: AttitudeObserver/attitude observer Y-axis/Gain6 */
   y_axis__DiscreteTimeIntegrator3 += ((In_attObs_angularRateY_RADs_dsp_value +
    (0.86493286641956202F * y_axis__Sum2) + y_axis__DiscreteTimeIntegrator1) * 0.003F);

   /* Discrete Integrator: integration
      # combined # Sum: AttitudeObserver/attitude observer Y-axis/Sum4 */
   y_axis__DiscreteTimeIntegrator1 += (0.27386127875258409F * y_axis__Sum2 * 0.003F);

   /* Saturation: AttitudeObserver/attitude observer X-axis/Saturation */
   if (In_attObs_accY_g_dsp_value > 1.2F) {
      Sc2_Saturation = 1.2F;
   }
   else {
      if (In_attObs_accY_g_dsp_value < -1.2F) {
         Sc2_Saturation = -1.2F;
      }
      else {
         Sc2_Saturation = In_attObs_accY_g_dsp_value;
      }
   }

   /* Trig: AttitudeObserver/attitude observer X-axis/Trigonometric Function4 */
   if (Sc2_Saturation < -1.F) {
      x_axis__TrigonometricFunction4 = -1.5707963267948966F;
   }
   else {
      if (Sc2_Saturation <= 1.F) {
         x_axis__TrigonometricFunction4 = (Float32) asin((Float64) Sc2_Saturation);
      }
      else {
         x_axis__TrigonometricFunction4 = 1.5707963267948966F;
      }
   }

   /* Sum: AttitudeObserver/attitude observer X-axis/Sum2
      # combined # Gain: AttitudeObserver/attitude observer X-axis/Gain6
      # combined # Discrete Integrator: AttitudeObserver/attitude observer X-axis/Discrete-Time Inte
      grator1 */
   x_axis__Sum2 = x_axis__TrigonometricFunction4 - ((0.F * x_axis__VI_Integrator) +
    x_axis__DiscreteTimeIntegrator2);

   /* Discrete Integrator: integration
      # combined # Sum: AttitudeObserver/attitude observer X-axis/Sum4
      # combined # Gain: AttitudeObserver/attitude observer X-axis/Gain5
      # combined # Discrete Integrator: AttitudeObserver/attitude observer X-axis/Discrete-Time Inte
      grator3
      # combined # Discrete Integrator: AttitudeObserver/attitude observer X-axis/Discrete-Time Inte
      grator1
      # combined # Discrete Integrator: AttitudeObserver/attitude observer X-axis/Discrete-Time Inte
      grator2 */
   x_axis__DiscreteTimeIntegrator2 += (((x_axis__VI_Gain[2] * x_axis__Sum2) + ((2.F *
    x_axis__DiscreteTimeIntegrator3) + (0.F * x_axis__VI_Integrator) + (-2.F *
    x_axis__DiscreteTimeIntegrator2))) * 0.003F);

   /* Discrete Integrator: integration
      # combined # Sum: AttitudeObserver/attitude observer X-axis/Sum4
      Variable 'x_axis__Sum4' replaced by 'Aux__b'
      # combined # Gain: AttitudeObserver/attitude observer X-axis/Gain5
      # combined # Gain: AttitudeObserver/attitude observer X-axis/Gain1
      # combined # Gain: AttitudeObserver/attitude observer X-axis/Gain4 */
   x_axis__DiscreteTimeIntegrator3 += ((In_attObs_angularRateX_RADs_dsp_value + (x_axis__VI_Gain[0]
    * x_axis__Sum2) + x_axis__VI_Integrator) * 0.003F);

   /* Discrete Integrator: integration
      # combined # Sum: AttitudeObserver/attitude observer X-axis/Sum4
      # combined # Gain: AttitudeObserver/attitude observer X-axis/Gain5
      # combined # Discrete Integrator: AttitudeObserver/attitude observer X-axis/Discrete-Time Inte
      grator1 */
   x_axis__VI_Integrator += (((x_axis__VI_Gain[1] * x_axis__Sum2) + (0.F * x_axis__VI_Integrator)) *
     0.003F);

   /* Sum: AttitudeObserver/attitude observer Y-axis/Sum1
      # combined # Discrete Integrator: AttitudeObserver/attitude observer Y-axis/Discrete-Time Inte
      grator6 */
   y_axis__Sum1 = In_attObs_angularRateY_RADs_dsp_value - y_axis__DiscreteTimeIntegrator6;

   /* Discrete Integrator: integration
      # combined # Sum: AttitudeObserver/attitude observer Y-axis/Sum3
      # combined # Gain: AttitudeObserver/attitude observer Y-axis/Gain2
      # combined # Discrete Integrator: AttitudeObserver/attitude observer Y-axis/Discrete-Time Inte
      grator5 */
   y_axis__DiscreteTimeIntegrator6 += (((25.605484963664036F * y_axis__Sum1) + (32.258064516129032F
    * y_axis__DiscreteTimeIntegrator5)) * 0.003F);

   /* Discrete Integrator: integration
      # combined # Sum: AttitudeObserver/attitude observer Y-axis/Sum3
      # combined # Gain: AttitudeObserver/attitude observer Y-axis/Gain2
      # combined # Discrete Integrator: AttitudeObserver/attitude observer Y-axis/Discrete-Time Inte
      grator4
      # combined # Discrete Integrator: AttitudeObserver/attitude observer Y-axis/Discrete-Time Inte
      grator5 */
   y_axis__DiscreteTimeIntegrator5 += (((10.162433333478599F * y_axis__Sum1) + ((5.8479532163742682F
     * y_axis__DiscreteTimeIntegrator4) + (-5.8479532163742682F * y_axis__DiscreteTimeIntegrator5)))
     * 0.003F);

   /* Discrete Integrator: integration
      # combined # Sum: AttitudeObserver/attitude observer Y-axis/Sum3
      Variable 'y_axis__Sum3' replaced by 'Aux__e'
      # combined # Gain: AttitudeObserver/attitude observer Y-axis/Gain2
      # combined # Gain: AttitudeObserver/attitude observer Y-axis/Gain1
      # combined # Gain: AttitudeObserver/attitude observer Y-axis/Gain4
      # combined # Discrete Integrator: AttitudeObserver/attitude observer Y-axis/Discrete-Time Inte
      grator4
      # combined # Discrete Integrator: AttitudeObserver/attitude observer Y-axis/Discrete-Time Inte
      grator7 */
   y_axis__DiscreteTimeIntegrator4 += (((19.218335351058514F * y_axis__Sum1) + (105.26315789473685F
    * In_attObs_torqueY_NM_engCtr) + ((-105.26315789473685F * y_axis__DiscreteTimeIntegrator4) +
    (105.26315789473685F * y_axis__DiscreteTimeIntegrator7))) * 0.003F);

   /* Discrete Integrator: integration
      # combined # Sum: AttitudeObserver/attitude observer Y-axis/Sum3 */
   y_axis__DiscreteTimeIntegrator7 += (19.218335351058514F * y_axis__Sum1 * 0.003F);

   /* Sum: AttitudeObserver/attitude observer X-axis/Sum1
      # combined # Discrete Integrator: AttitudeObserver/attitude observer X-axis/Discrete-Time Inte
      grator6 */
   x_axis__Sum1 = In_attObs_angularRateX_RADs_dsp_value - x_axis__DiscreteTimeIntegrator6;

   /* Discrete Integrator: integration
      # combined # Sum: AttitudeObserver/attitude observer X-axis/Sum3
      # combined # Gain: AttitudeObserver/attitude observer X-axis/Gain3
      # combined # Discrete Integrator: AttitudeObserver/attitude observer X-axis/Discrete-Time Inte
      grator5 */
   x_axis__DiscreteTimeIntegrator6 += (((25.834945021426769F * x_axis__Sum1) + (33.003300330032999F
    * x_axis__DiscreteTimeIntegrator5)) * 0.003F);

   /* Discrete Integrator: integration
      # combined # Sum: AttitudeObserver/attitude observer X-axis/Sum3
      # combined # Gain: AttitudeObserver/attitude observer X-axis/Gain3
      # combined # Discrete Integrator: AttitudeObserver/attitude observer X-axis/Discrete-Time Inte
      grator4
      # combined # Discrete Integrator: AttitudeObserver/attitude observer X-axis/Discrete-Time Inte
      grator5 */
   x_axis__DiscreteTimeIntegrator5 += (((10.111782421541163F * x_axis__Sum1) + ((5.8479532163742682F
     * x_axis__DiscreteTimeIntegrator4) + (-5.8479532163742682F * x_axis__DiscreteTimeIntegrator5)))
     * 0.003F);

   /* Discrete Integrator: integration
      # combined # Sum: AttitudeObserver/attitude observer X-axis/Sum3
      Variable 'x_axis__Sum3' replaced by 'Aux__d'
      # combined # Gain: AttitudeObserver/attitude observer X-axis/Gain3
      # combined # Gain: AttitudeObserver/attitude observer X-axis/Gain2
      # combined # Gain: AttitudeObserver/attitude observer X-axis/Gain8
      # combined # Discrete Integrator: AttitudeObserver/attitude observer X-axis/Discrete-Time Inte
      grator4
      # combined # Discrete Integrator: AttitudeObserver/attitude observer X-axis/Discrete-Time Inte
      grator7 */
   x_axis__DiscreteTimeIntegrator4 += (((19.218335351058546F * x_axis__Sum1) + (105.26315789473685F
    * In_attObs_torqueX_NM_engCtr) + ((-105.26315789473685F * x_axis__DiscreteTimeIntegrator4) +
    (105.26315789473685F * x_axis__DiscreteTimeIntegrator7))) * 0.003F);

   /* Discrete Integrator: integration
      # combined # Sum: AttitudeObserver/attitude observer X-axis/Sum3 */
   x_axis__DiscreteTimeIntegrator7 += (19.218335351058531F * x_axis__Sum1 * 0.003F);
}

/*----------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/
#endif /* ATTITUDEOBSERVER_C */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
